---
title: Chicago Bears
author: ''
date: '2020-09-04'
slug: chicago-bears
categories: []
tags: []
---
Throwing good money after bad. The sunk cost fallacy. When someone continues an endeavor as a result of previously invested resources, rather than objectively viewing rookie quarterback highly, watch as the team’s performance isn’t tragic despite mediocre bc
future decisions based on their own cost-benefit. Far too often, we see teams draft a quarterback play, and then reward said quarterback with a second, more lucrative.

After Carr’s first two years, the team went 10-22 and he averaged only 6.2 YPA. But thanks to a 12-3 season in 2016 (he only averaged 7.0 YPA) the Raiders tore up the final
year of his rookie deal and rewarded him with a $125 million contract. The team hasn’t
had a winning record in any of the first three years he has been on the new deal.

After Joe Flacco led the Ravens to the Super Bowl win over the 49ers in the 2012
season, the Ravens were in a bind. Flacco was a fine quarterback and clearly did exactly
what the team needed him to do on his rookie deal. But that’s when his cap hits were low and he was averaging $5.95 million per year. But off the Super Bowl, the Ravens were compelled to pay him. The first three years of his six-year deal, he averaged just 6.8 YPA and the Ravens posted one winning season.
And that was during a period when Flacco’s cap was somewhat manageable (in the $14 million range). The next two years of his deal, his cap hit was set to hit $28.6 million and.

The Ravens still didn’t feel they could cut bait but had to do something. So they gave Flacco a $40 million signing bonus and signed him to a new contract, which lowered his 2016 and 2017 cap hits into the $22 to $24 million range. It didn’t help enough. Just like the first three years of his first non-rookie deal, the Ravens posted one winning record in those next three years before Flacco gave way to Lamar Jackson, as the one-time Super Bowl winner averaged only 6.2 YPA over those three years.

After Bortles’s career started with three straight years of terrible play and terrible records (11-34 in total), the Jaguars defense led them to a 10-6 record in 2017 and the AFC Championship game. Bortles averaged just 7.0 YPA with an 84.7 rating, but the team decided to sign him long-term instead of letting him play out his fifth-year on the option. It was a costly mistake (giving him the fifth-year option itself was an error that snowballed into future bad moves). Bortles went 3-9 in 2018 and averaged 6.7 YPA in the process, and that was when his cap hit was still only $10 million. Prior to his cap hit heading north of $21 million, the Jaguars cut him.
The story was similar with Andy Dalton and I could name a number of other quarterbacks as well. The point being, when these guys are on rookie deals, it’s easier to build a winner around them. Even if they aren’t great, through the sheer cycles of the NFL and natural variation, these guys could lead the team to an improbable playoff run.
That does not mean he’s worthy of a lucrative extension. In fact, giving him such an extension handcuffs the team and makes you less likely to win, as we saw with Carr, Flacco, and Bortles.
We discussed this very point on the NFL panel I was on at the 2019 Sloan Sports Analytics Conference with Mina Kimes. There really hasn’t been a precedent of cutting bait with a highly-drafted quarterback after somewhat decent team results. But should there be? When it was my turn I threw out Mitchell Trubisky’s name, and said:
“Where do we see this guy’s development in year four? One of the big problems that teams have is you have a team that is successful with a quarterback on his rookie deal so it’s easier to build your team. In his last year, do we pay this guy? Or do we let him walk and now we might be worse next year? What is that going to say to the fans and what is the public perception going to be of our team’s strategy at that point?”
“The league has been getting more aggressive in free agency, and I would like to see a team [with a highly-drafted but mediocre quarterback on a rookie deal] try to be aggressive from that perspective and not care about the repercussions from public perspective.”
Trubisky’s rookie year was a disaster. But in the first year with Matt Nagy (Trubiksy’s sophomore season), Nagy took Trubisky under his arm and allowed the quarterback to shine with a new offense. The Bears went 11-3 in Trubisky’s starts and he averaged 7.4 YPA.

But in last year’s chapter on the Bears, I warned about the “sophomore jump” in quarterback production, which we’ve consistently seen as second-year quarterbacks make gargantuan leaps in efficiency compared to their rookie season. I focused on that element coupled with the Bears tough salary cap, and forecast a return to Earth for the 2019 Bears off that 12-4 season of 2018. And that is exactly what happened.
Before diving into the 2019 season deeper, the biggest change this offseason was the team trading for quarterback Nick Foles. This type of move is exactly what I lobbied for over a year ago at Sloan — acquiring a veteran quarterback when your rookie-deal quarterback was clearly not the long-term answer and not someone you should dump money into on a second deal. And ignoring whatever the public might think about potentially having wasted a high draft pick (No. 2 overall in this case, with a trade up) on a quarterback.

But their defense did not have the same type of success. Pressure tends to create the most takeaways, be it via sack-fumbles or problematic passing leading to interceptions, tipped balls, or inaccurate passes leading to interceptions on deflections. The 2018 Bears recorded 50 sacks. The 2019 Bears recorded just 32. When adjusting to offensive sacks allowed, the Bears went from a net +17 sack margin in 2018 to a -13 sack margin. That’s a swing of 30 sacks.
There have been only 27 teams in the last 30 years to see a swing of -30 sacks from one year to the next before the 2019 Bears. Every single one of these teams lost more games the following year except one. On average, these teams lost four more games the following season, identical to the 2019 Bears as they dropped from 12 wins to only eight wins.
The Bears dropped from 15th in third down conversion rate in 2018 to 25th in 2019. The driver was largely distance to go: on average, in 2018 they needed 6.3 yards on third down (sixth-fewest) and in 2019 that increased to 7.1, 14th fewest. The Bears must be more efficient on first down to shorten the distance to go.
In order to be more efficient, the Bears should both increase their pass rate and improve the run types that lead back David Montgomery is best at executing. On first down through the game’s first three quarters, the Bears passed the ball on 50% of play calls, the 11th most frequent in the NFL. Their 57% success rate was above average on such passes, while their 43% success rate on run plays was well below average. Of 137 RB-runs on first down, Montgomery took 104 of them. He averaged just 3.8 YPC and a 41% success rate. He was terribly inefficient running outside zone (2.6 YPC, 38% success) and only slightly better running inside zone, which accounted for over a third of all first down runs (3.9 YPC, 44% success). Montgomery’s most efficient runs from an EPA, success rate, or YPC perspective had a lead blocker. He gained 5.5 YPC with a 64% success rate on 22 lead runs. These were primarily from 21 or 12 personnel.
Also interesting was the drop in production from the run game in the red zone in 2019. In 2018, Trubisky recorded a 100% success rate in red zone runs and scored three touchdowns on six carries. The team didn’t build on that production in 2019, as he had just six carries, and these were successful just 33% of the time (one TD). Montgomery’s 35% success and 1.7 YPC paled in comparison to Jordan Howard’s 69% success and 3.2 YPC from 2018. One of the few places on the field where rushing is efficient is inside the red zone and the Bears must fix their red zone rushing offense in 2020.

It won’t be easy. While the addition of a new quarterback was smart. The implementation was not nearly as smart. Despite quarterbacks like Jameis Winston and Cam Newton sitting as free agents, the Bears went aggressively after Foles. They sent a fourth-round pick to the Jaguars and didn’t require Jacksonville to take on any part of Foles’s contract. When former starters like Winston, Newton, and Andy Dalton were had for nothing, it seemed illogical for the Bears to be that aggressive. This should tell us all we need to know about what the Bears plans are at the quarterback position in 2020.
The Bears also made the robust move of signing Jimmy Graham to a two-year, $16M deal. I realize the Bears lost Adam Shaheen and Trey Burton to injuries last year. But Graham is a liability in pass protection and may not get used enough as a receiver to make such a contract worth it. Chicago also has eight other tight ends on the roster at a combined $10.3M this season. Even in Weeks 1-9, when both Shaheen and Burton were playing, the Bears used 12 personnel only 14% of the time, sixth-least in the NFL. And the Bears targeted tight ends only 11% of the time in 2019, the third-lowest rate in the NFL.
The Bears also must improve in their usage of running backs in the pass game. Last year they threw 29% of all passes on early downs with 10+ yards to go to their backs. That was the fourth-highest rate in the NFL. But unlike two teams with very high target rates, such as the Patriots and Chargers, these targets were terribly inefficient. On such targets, the Bears averaged 4.5 YPA (30th) and a 40% success rate (28th). Compare that to the Chargers, who led the NFL in running back target rate, who were at 8.0 YPA (fifth) and a 56% success rate (fifth). The Patriots were one of the best teams in the league at 8.4 YPA (second) and a 59% success rate (first). Either the plays designed for these targets are in need of massive improvement or the Bears need to seek to target backs much less in these situations.
In 2020, Chicago faces a very similar schedule to last year based on overall strength, but there is some reason for optimism. Last year I forecast the Bears to have the fifth-toughest schedule using my methodology in May. Looking at their actual schedule strength when all was said and done, the Bears faced the seventh-toughest schedule, so my ranking was extremely prescient for them. This year, I forecast they will play the sixth-easiest schedule. That projected improvement in schedule strength of 20 ranking spots is second-most in the NFL. Their three most difficult non-division games are all at home: against the Colts in Week 4, Bucs in Week 5, and Saints in Week 8. But all of those dome/warm weather teams will avoid the cold Chicago winter, given their trips to Chicago are Week 8 or earlier. The Bears are fortunate to host dome teams of the Vikings, Lions, and Texans from mid-November onward. Chicago is 20-7 (74%) and 19-7-1 ATS (73%) at home from Week 10 onward vs dome or warm weather teams since 2005, including 5-0 the last two years. The Bears surprisingly play four primetime games, and in one of those games, they have to play the Rams in LA on Monday night in Week 7. That puts them into a very disadvantageous position – a non-West Coast team playing in primetime on the West Coast. It also sets them up to face the Saints on a short week. Additionally, they play the Buccaneers on a Thursday night. The good news is they host the game, but the bad news is that on short weeks, the better team has more of an edge than does the home team: home underdogs win just 25% of games and cover 38% on three days rest.
If the pairing of Lazor and Foles can work wonders, the Bears absolutely can be better than the 8-8 mark from 2019. But Chicago’s roster is severely stressed from a cap perspective and there is little room for error.

The Chicago passing game was bleak in 2019. They did respectively rank 18th in the league in success rate (44%), but that came along with ranking 30th in the league in yards above successful rate, and 31st in the league in yards per passing play (5.3 yards), which landed them at 26th in the league in total EPA via the air. Third-year quarterback Mitchell Trubisky took a major step backward in 2019, ranking last in the league in yards per pass attempt from a clean pocket (6.6 Y/A) and second to last in yards per attempt under pressure (4.6 Y/A) for all qualifying passers. Bypassing the pickup of his fifth-year option, the Bears went out and traded for Nick Foles as immediate competition in 2020. Foles is on his fifth team in six seasons and has not thrown 200 or more passes in an NFL season since 2015 with the Rams, but the Bears are not committing to waiting on Trubisky’s development any longer.

Given the quarterback situation in Chicago, it is no surprise that their receiving targets rank among the bottom of the league. The Bears ranked 26th in the league in yards per attempt to their wide receivers (7.2 yards), while 31st in the league in yards per attempt to their tight ends (5.5 yards) and running backs (4.5 yards). One of the lone bright spots was Allen Robinson, who caught 98 passes for 1,147 yards and seven touchdowns. Second-year wideout Anthony Miller also came on to close the season, catching passes for 438 yards and two touchdowns over his final seven games of the season. Chicago tight ends combined for just 46 catches for 416 yards and two touchdowns last season, adding 33-year-old Jimmy Graham and Cole Kmet.

It was not just the Chicago passing game that struggled in 2019, but their rushing game also followed suit. The Bears collectively ranked 25th in rushing success rate (44%), 31st in yards created above success rate, and rounded things out by finishing 29th in EPA via the ground and in yards per carry (3.7 yards). Rookie David Montgomery was a mixed bag, registering 1,074 yards from scrimmage and seven touchdowns, but he averaged just 4.0 yards per touch. Where Montgomery struggled was creating explosive runs, registering gains of five or more yards on just 28% of his carries (league rate was 34%) and 10 or more yards on 7% of his carries (league rate was 10%). As a team, the Bears finished ahead of only the Dolphins and Jets in rushing gains of 10 or more yards on the season.

Is there anything of note in the Chicago Passing Game in 2020?
Playing a full 16 games for the first time since the 2016 season, Allen Robinson delivered a WR8 season in PPR scoring overall and WR11 season in points per game. As a one-man-band, Robinson caught 98-of-154 targets for seven touchdowns. At the wide receiver position, only Michael Thomas and Julio Jones received more targets than Robinson, who accounted for 26.6% of the Chicago targets, a usage rate which trailed only Thomas and DeAndre Hopkins among all wideouts. Robinson did average just 11.7 yards per reception, his lowest rate since his rookie season, but posted a career-high 63.6% catch rate as the Bears found ways to get him the football, using him in the slot on 40% of his routes in each of his two seasons there. Transitioning to a volume-based target over a splash-play option, Robinson is elevated as a WR1 in full-PPR formats while losing some ground as a WR2 in standard leagues.
Anthony Miller has posted nearly identical catch rates (61.1% and 61.2%) and yards per catch (12.8 yards and 12.6 yards) over his first two NFL seasons. After outkicking his expected touchdown total as a rookie, Miller found the end zone just two times in 2019, but jumped from 54 targets as a rookie up to 84 a year ago. Miller particularly showed signs of life late in the season. After catching just 17-of-30 targets for 218 yards and zero touchdowns on 9.6% of the team targets through nine games, Miller caught 35-of-55 targets for 438 yards and two touchdowns on 18.5% of the Chicago targets over his final seven games. Taylor Gabriel appeared in just two of those games, but was not brought back this offseason while the Bears added Ted Ginn. Miller’s end of season usage should rollover, the only question remains is how often the Chicago quarterback situation will support the depth behind Allen Robinson. Even during his spike down the stretch, Miller had weeks with just four, two, and one target.
I bring up both Robinson and Miller because the Bears project to face our seventh-easiest passing schedule blend in the NFL this upcoming season. Both Robinson’s full season and Miller end of the season were viable for fantasy while playing alongside an anemic Mitchell Trubisky, so both can overcome poor quarterback play no matter who should win the quarterback competition in Chicago.
There is a strong bet that both Trubisky and Nick Foles play, but if one of the two passers is going to be more viable in 2020 for fantasy on their own merit, the answer between the two is Trubisky.
Trubisky has been a really strong fantasy option versus poor defenses. In 17 career games against pass defenses that rank 20th or lower, Trubisky averages 23.3 fantasy points per game and 8.5 yards per pass attempt as opposed to 14.2 fantasy points and 5.7 yards per attempt otherwise. Even a year ago, those marks were 21.9 points per game in five games versus those lower-end pass defenses and 7.9 Y/A versus 14.3 points per game and 5.3 Y/A outside of those weeks. Trubisky even had three top-eight scoring weeks last year versus the Lions and Giants in his three games versus those teams a year ago, who are the opening two opponents for the Bears this season.

Akiem Hicks has been a world-beater along the defensive line but missed most of last season with multiple injuries. In his absence, both Eddie Goldman and Roy Robertson-Harris played well. Goldman was the prototypical run stuffer and Robertson-Harris added some pass rush production. Abdullah Anderson also had a high pressure rate from the interior on a limited number of snaps. This is a deep group, but Hicks will be 31 in 2020, though Goldman just turned 26 and Robertson-Harris will turn 27 in July.
The Bears gave up a lot of draft picks for Khalil Mack. Mack has been everything the Bears hoped, but only one edge rusher could do so much. Chicago doubled down on the pass rush by giving a massive $30 million guaranteed to Robert Quinn this offseason. Quinn has been an ESPN Pass Rush Win Rate darling for the past two seasons, but the Bears still made a heavy investment for a No. 2 rusher who will turn 30 in July. Barkevious Mingo is the type of third pass rusher who could easily be replaced.
Both Roquan Smith and Danny Trevethan missed time in 2019 but when healthy they can be one of the better linebacker duos in the league. Trevethan is still a good run stopper but has only played one 16 game season since he came to Chicago. While he turned 30 years old in March, he also signed a new three-year contract. After Nick Kwiatkowski left in free agency, there is little depth behind the top-two and the Bears played 30% of their defensive snaps in base last season.
Both Kyle Fuller and Buster Skrine were average cornerbacks last season by Adjusted Yards allowed per coverage snap but the Bears will miss Prince Amukamara, who was the team’s best corner (but is still a free agent). Artie Burns was a free agent signing, who the Bears hope will benefit from a change of scenery. Burns fell out of favor with the Pittsburgh coaching staff the past season and played just 9.3% of the defensive snaps for the Steelers in 2019 and was a healthy scratch for the final four games of the season. Second-round pick Jaylon Johnson should also figure into some snaps throughout his rookie season.
Eddie Jackson is great. That’s also where the Bears’ safety depth stops. Chicago brought in Tashaun Gipson after an up and down year with Houston. After that, the Bears have a number of special teamers and castoffs. Deon Bush hasn’t played more than 15.5% of the team’s defensive snaps since he played 45% his rookie season in 2016. Jordan Lucas has been mostly a special teamer for his four seasons between two teams. Kentrell Price wasn’t on a team in 2019 and was cut from the Seattle Dragons of the XFL in minicamp. DeAndre Houston-Carson’s career-high rate in defensive snaps is 5.3%.