---
title: Pittsburgh Steelers
author: ''
date: '2020-09-04'
slug: pittsburgh-steelers
categories: []
tags: []
---


Between their lack of implementing valuable offensive strategies and simply watching
their brand of uninspiring football every Sunday, the Steelers were one of the most
frustrating teams to watch in 2019. If it was frustrating watching them as an analyst, I
cannot imagine how it was to be a fan.
And we will get to the bad soon enough. But before we do, let’s take a moment to
acknowledge how insane it was that the Steelers finished 8-8 and not significantly worse .last year.
This was a team that lost Ben Roethlisberger six quarters into the season.
This was a team that sat 0-2 and needed to name a new starter for their Week 3 game. A

game on the road against the team that would hold a 10-point fourth quarter lead in the
Super Bowl, the San Francisco 49ers. They dropped that game.

And yet over their final 13 games, of which Mason Rudolph started seven and Duck .
Hodges started six, neither backup quarterback recorded a losing record. Together, the 
Steelers produced an 8-5 record over those games.
It was a gross season for quarterback play on the Steelers, but even beyond that duo,
this offense had virtually nothing.
• A third-round rookie from Toledo, Diontae Johnson, was their leading receiver.
• A fourth-round rookie from Kentucky, Benny Snell, was eight carries shy of being their leading rusher.
One would figure with such terrible options at quarterback and in the receiving game, this team would need to rely on rushing touchdowns to score points.

But they only scored a total of seven touchdowns on the ground all season.
Among teams to post final records at or above .500 over the past 20 years, only 4% scored seven or fewer rushing touchdowns.
Despite the lack of a quarterback, despite the lack of receiving weapons, despite the lack of rushing production
how were the Steelers sitting at 8-5 and in the playoffs through Week 14?
There are a few key “singular event” statistics that correlate extremely strongly with wins: • Winning the turnover battle = 79% wins
• Winning the sack battle = 71% wins
• Scoring a non-offensive TD = 71% wins
Forget everything else that happens in games. When you win these battles, you often win the war. They don’t guarantee anything, however, they aren’t 100% wins.
But for the Steelers, they were 100% losses if they didn’t win these battles.
• Unless the Steelers won the turnover battle, they were 0-5.
• Unless the Steelers won the sack battle, they were 0-5.
• In six games, they didn’t win the turnover battle, sack battle, or both. They went 0-6.
In 10 games they won both the turnover battle and sack battle, they went 8-2. Compare these numbers to the prior two years, where the Steelers went 17-10-1 when not winning the turnover battle, sack battle, or both (0-6 last year).
However, in those prior two years, only five times did the Steelers win both the turnover and sack battle (5-0). Compare to 10 times last year alone.
How did they win the turnover battle so often in 2019? (The defense was incredible, but we’ll dive in there later.)
First, the Steelers had a ton of luck. Specifically, fumble luck. Pittsburgh recovered 5.6 fumbles over expectation (FROE), which was the best in the NFL. While the Steelers fumbled 30 times on offense, they recovered 63% of those fumbles. They created 33 fumbles on defense, and recovered 54.5% of those. Stripping the ball can be a skill, but once that odd-shaped football starts bouncing on the carpet, a lot of luck gets involved in recovery. And the Steelers were the luckiest team in the NFL in that capacity.
They also had other things go their way. They were 4-0 when scoring a non-offensive touchdown, such as a defensive turnover for a touchdown or a punt/kick return.
Pittsburgh was also the fourth-best team in field goal luck. While the kicking unit was great offensively (a skill) and made 94% of field goals, the Steelers were fortunate that opponents only made 81% of field goals against them. It was the fourth-best net in the NFL. Compare to 2018, where they had the fourth-worst net in the NFL.
This was a big part of how the Steelers finished 8-8 despite the massive talent disadvantage. Another huge element was the fact they faced the fourth-easiest schedule of opposing run defenses. They played five games against teams ranked 27th or worse against the run and won four of the five, or half their wins on the entire season.
Another element that helped win eight games was the strength of their running back pass game. The Steelers ranked top-10 in virtually every RB-pass metric and bottom-5 in virtually every wide receiver or tight end pass metric. Whereas the Patriots totaled 167 air yards on 120 completions to running backs (most in the
NFL), the Steelers totaled -112 air yards on 91 completions to RBs, second-worst. The Steelers still totaled the ninth-most EPA/att on these running back targets despite their conservative, behind-the-line target rate.
Compare the positional EPA recorded by the 2019 Steelers passing offense:
• WRs: -20.6 EPA (32nd), 42% success rate (32nd)
• TEs: -0.6 EPA (31st), 43% success rate (31st)
• RBs: 13.1 EPA (ninth), 51% success rate (seventh)
And the final huge element that helped win eight games was their offensive line. In the five years with Mike Munchak as offensive line coach, the Steelers ranked top-10 in offensive line performance (average of pass blocking & run blocking ranks) every single season. But he left for Denver and I had my concerns about the offensive line. And sure enough, based on Adjusted Line Yards and Adjusted Sack Rate, the Steelers dropped out of the top-10 last season. Last year, the Steelers allowed 32 sacks on 505 QB attempts (6.3%), as compared to 24 sacks on 687 QB attempts (3.5%) in 2018.

However, we need to consider more than just the team-based stats when evaluating offensive line play. Based on ESPN’s Pass Block Win Rate, the Steelers ranked seventh in the NFL. The metric measures the rate at which linemen can sustain their blocks for 2.5 seconds, and the Steelers o-line did it at a 62% rate on average. This was actually an improvement over the 2018 Steelers line, which ranked 17th. Looking at PFF grades, the Steelers ranked fifth in pass blocking, down from third in 2018, but still solid.
We see in these numbers the impact of quarterback play and decision making, and how much they can control pressure and sack rates. Behind solid o-line play in 2018, Roethlisberger helped the team to the fourth-lowest sack rate. Behind comparable o-line play based on player tracking and player grades in 2019, Rudolph and Hodges led the Steelers to almost double the sack rate as 2018.
In 2018, the Steelers saw the left side of the line intact for all 16 games (LT Alejandro Villanueva, LG Ramon Foster, and C Maurkice Pouncey). RT David DeCastro played 14 games but RT Marcus Gilbert played only five games so RT Matt Feiler filled in for 10 games.
In 2019, the Steelers didn’t have the same health along the left side of the line. While Villanueva played all 16 games, Foster played 14 and Pouncey played 13. On the right side of the line, DeCastro was healthy for all 16 games, but the real story was the surprising Feiler. The undrafted kid out of Bloomsburg University, who had played RT for the first time in his NFL career in 2018, not only started all 16 games at RT in 2019, he recorded the best overall passing grade of any Steelers lineman. In 2020, the o-line continuity takes another hit, with journeyman Stefen Wisniewski taking over at LG from Ramon Foster who retired.
So, what about the bad. What did the Steelers do poorly that was frustrating to watch and to recap after the season? For starters, it’s the lack of play-action.
Play action helps the passing games immensely. On early downs in a game’s first three quarters last year, 3,497 passes with play-action totaled 504.1 EPA. But 5,784 passes without play-action totaled -67.9 EPA. That’s the single best data point to show how valuable it is to offenses. Splits across multiple metrics per play: Without a starting quarterback, and with an offense that needed to be more balanced and ground-oriented than most out of necessity, one would think this would be the prime opportunity to use more play action. But in 2019, the Steelers used play-action on the fewest plays in the NFL and the least often of any team.
In unfortunate news for Steelers fans, even with Roethlisberger in 2018, they used play-action least of any team. While most of the league is taking advantage of using more and more play-action for the benefits it provides, the Steelers seem dead set on ignoring it as much as possible. It’s a huge mistake. It doesn’t matter who you have in the backfield or at quarterback – we can measure linebacker movement and say with certainty that play-action influences second-level defenders, opens throwing lanes, and improves passing efficiency. If an offensive coordinator chooses to ignore that or not build an offense to generate success against the defense’s weaknesses, it’s not just an opportunity lost, it’s a shame.
Then, there was the lack of pre-snap motion. The Steelers used pre-snap motion ahead of just 34% of plays in quarters 1-3. That ranked seventh-least in the NFL and well below the 43% average. Pre-snap motion helps a quarterback identify coverage before the snap, to allow him to choose the matchup that will have the best odds of success or manipulate that matchup. It discerns man or zone coverage. And the quarterback can also adjust the play after the motion, a la Tom Brady.
In fact, the five teams that used the most pre-snap motion ahead of passes last year:
KC: Super Bowl champions & AFC No. 2 seed
SF: Super Bowl & NFC No. 1 seed
TEN: AFC Championship & AFC No. 6 seed
BAL: Best regular season record & AFC No. 1 seed NE: AFC No. 3 seed
Pre-snap motion is free and takes no talent. Just run your man laterally and see how the defense adjusts. Take the free information and profit. Just like play-action (which is also free and takes no talent) the Steelers choose to ignore the edge it provides an offense.
Then, there was the predictability. With how tilted the rulebook is to offenses in the modern game, particularly passing offenses, it is rare for a defense to have the upper hand. Sometimes you’ll have a huge talent disparity between offense and defense. But barring that, most often when defenses “win” a play, it’s the result of the offense
shooting itself in the foot, whether it’s a failure to execute, breakdown, or miscommunication.

With Ben Roethlisberger lost for the season after just six quarters into the 2019 season, the Steelers passing game was compromised and their depth at the quarterback was exposed. With Mason Rudolph and Devlin Hodges pressed into action, the Steelers ranked last in the NFL in success rate through the air (39%). Slightly better than dead last, they did rank 28th in yards per passing play (5.5) and 28th in EPA on the season via their passing offense. The team went from 313 passing yards per game in 2018 down to 186.3 passing yards per game in 2019, the largest single-season decline of passing yardage per game in league history. Rudolph and Hodges turned the ball over 17 times via interceptions compared to 18 touchdown passes. Roethlisberger will be 38 years old and coming off elbow surgery, but has a low bar to clear improving the Steelers’ passing game output in 2020.

As a byproduct of the quarterback situation, the Steelers’ wide receivers ranked 18th in success rate (49%) and their tight ends ranked 20th (51%). But despite being limited by quarterback play, the Pittsburgh wideouts still ranked ninth in yards per target (8.2) and third-round rookie Diontae Johnson led all NFL rookies with 59 receptions. No player felt the sting of losing Roethlisberger more than JuJu Smith-Schuster. In his first season as the lead receiver for the team, Smith-Schuster missed four games due to injury and finished 78th out of 84 qualifying wide receivers in success rate per target (42%). With Roethlisberger and a young nucleus of Smith-Schuster, Johnson, James Washington plus Eric Ebron, expect more aerial production.

The Pittsburgh passing offense was so anemic in 2019 that it masked the fact their running game was just as bad. Pittsburgh was last in the league in Expected Points Added via their rushing game, 29th in success rate (43%) and 29th in yards per play (3.7 yards). Another area where the Steelers’ depth chart was exposed a bit was at the running back position. Durability has been an issue for James Conner over the past two seasons with nine games outright due to injury and fewer than 40% of the team snaps in 10 of his 23 games active. With Conner missing time last year, the duo of Jaylen Samuels and Benny Snell totaled 929 yards on 214 touches while Conner produced 715 yards on his 150 touches. Pittsburgh added explosive playmaker Anthony McFarland in the draft this spring to insure and compliment Conner.

Take the Discount on JuJu Smith-Schuster
Playing just six quarters with Ben Roethlisberger and missing four full games, we came away with more questions about Smith-Schuster’s status as an elite fantasy wide receiver without the presence of Antonio Brown than answers. His per-game output (3.5 receptions for 46.0 yards) was nuked. Coming off of last season’s bitter taste, it is easy to forget Smith-Schuster is still one of the most precocious wideouts in the league even factoring last season’s production. Smith-Shuster does not turn 24-years old until November and is only 683 yards away from having the most receiving yards prior to turning 24 in league history. The emergence of Diontae Johnson also allows Smith-Schuster to keep working primarily through the slot, as his 66.3% slot rate in 2019 was a career-high. As a player that was in the running to be a top-five pick at his position a year ago with one of the most decorated early careers ever at his position, a fourth-round price reduction allows you to take advantage of the disappointment of last season when everything went wrong while offering some insulation should he fail to completely reach 2018 levels of output.
Player to target: Diontae Johnson
While you should explore the discount on Smith-Shuster, Diontae Johnson may be the best value in this offense overall. For as bad as the Pittsburgh offense was in 2019, Johnson was a rose that grew out of the concrete. Johnson led all rookies with 59 receptions (690 yards and five touchdowns) while contributing 12.4 yards per punt return with a touchdown. Per NFL Next Gen Stats, Johnson led all NFL wide receivers in average yards of separation (3.6) per target. With similar universal skill sets that remind of the Antonio Brown, Emmanuel Sanders, and Santonio Holmes receiving corps from seasons past, Johnson can make a significant stride forward with actual quarterback play in 2020.
Ben Roethlisberger is a Strong Late Round QB Target
We still do not know what fantasy life for Roethlisberger looks like without a prime Antonio Brown, but the Steelers have a young pass-catching nucleus filled with upside while the Steelers draw our No. 2 easiest projected passing efficiency schedule for the full season and our third easiest schedule in the same department over the opening four weeks of the season. Finishing as the QB9 or higher in points per game in each of the three prior seasons to 2019, Roethlisberger should not be overlooked as a solid starting option that will come cheaply for those players waiting on the position.

No defense bailed out its offense more than the Steelers in 2019. Despite having the 27th worst starting field position, Pittsburgh finished the season third in points and yards allowed per drive. Much of that was due to a league-high turnover rate that will be unlikely to repeat in 2020. Still, there’s a lot of talent on every level of this defense.
Even after losing Javon Hargrave to the Eagles in free agency, the Steelers have one of the strongest interior lines in the league with Cameron Heyward and Stephon Tuitt, though Tuitt played just six games last season and ended the year on IR. Both have the ability to rush the passer and can kick outside in a four-man front if necessary. Pittsburgh already made a move to add positional depth with a rare intradivision trade that brought Chris Wormley over from the Ravens. Wormley just has one year remaining on his rookie contract, though, but provides added depth for 2020.
T.J. Watt is already one of the league’s best pass rushers. He was second in ESPN’s Pass Rush Win Rate last season and was second in pressure rate, per SIS. The Steelers franchised Bud Dupree after he finally broke out in his fifth season. There’s a question around how committed the Steelers are to Dupree and that might need to be answered given how much Pittsburgh relied on their two edge rushers last season. Dupree played 90% of the defensive snaps and Watt played 86%. There’s little depth of note behind them outside of 2020 third-round pick Alex Highsmith of Charlotte.
Devin Bush was an instant impact starter at off-ball linebacker last season but the Steelers also relied on Mark Barron for nearly 70% of the defensive snaps as an inside linebacker. He wasn’t particularly effective but without Barron on the roster those are still snaps that need to be accounted for and not much was added at the position. Pittsburgh could give a bigger role to Vince Williams, who flashed with limited playing time. His coverage was solid and he was an effective blitzer with a 29% pressure rate on 48 pass rush snaps, per SIS.
Joe Haden and Steven Nelson played as one of the league’s best corner duos last season; both allowed a sub-1.0 Adjusted Yards per coverage snap. Mike Hilton was the weak link as the slot corner, but Cameron Sutton was a star in limited playing time across the secondary. Justin Layne also has promise as a long third-round pick from 2019. This is one area where the Steelers have high-level play and depth. Sixth-round pick Antoine Brooks is listed as a safety, but could profile into a Barron-type role in the NFL.
Like every position expect corner, the Steelers have a good top duo they rely on often with little depth behind the starters. The acquisition of Minkah Fitzpatrick was a season changer for the defense but it also limited what Pittsburgh could use to build depth behind him. 2019 first-round pick Terrell Edmunds bounced around from deep safety to the slot but could use a little more development in coverage.

The only one thing an offense can do to give the defense an upper hand is predictability. There is no room for predictability on offense in today’s game. It’s one thing for an offense to do something so well that they keep repeating it until the defense stops it. But as you’ll see, that wasn’t the case for the Steelers. These predictable lineups resulted in below-average production, even for the 2019 Steelers.
When Jaylen Samuels was on the field, the Steelers passed 75% of the time. These passes averaged 4.9 YPA.
When Benny Snell was on the field, the Steelers ran 78% of the time. These rushes averaged 3.5 YPC.
And if Johnny Holton was on the field at the same time as Snell, it was a run on 67 of the 73 play calls – 92% of the time. These rushes averaged 3.1 YPC
These rates are far too predictable, particularly for a team with poor quarterback play that couldn’t afford to be at all predictable. The reasoning behind the decisions made sense: Benny Snell was a rookie and the Steelers didn’t trust him to pass block. He only pass blocked on eight of 167 total snaps. But Samuels, a second-year back with more pass blocking experience with time at tight end in college, was adept at receiving and pass blocking. The problem is, defensive coordinators get excited when you share trends that are accurate 67% of the time. When you’re talking 75% to 90% accuracy over the course of a season? They’re going to make you pay for such predictability.
This offseason, the Steelers added Matt Canada as a quarterbacks coach. But he’ll do more than that. Mike Tomlin said he’s going to bring “fresh ideas, new schematic ideas” and will have input on offensive game plans.
Under OC Randy Fichtner, the Steelers used a lot of 11 personnel, didn’t use play-action, and rarely used pre-snap motion. Canada always crafts his offenses to the personnel he has. For example, his recent stops included spread sets with a dual-threat quarterback (Northern Illinois), a heavy power rushing attack (Wisconsin), as well as working pro-style with the Pitt Panthers and at NC State. He uses a lot of personnel groupings, a lot of shifts and motions, read-options and varies his tempo.
Keep in mind – Canada coached both James Connor at Pitt and Jaylen Samuels at NC State, and produced massive years for each. The Steelers offense under Fichtner in 2018 was top-5 but they didn’t squeeze enough juice from the orange. His 2019 offense showed limitations without exceptional talent. I wonder how these two offensive minds will co-exist because I can see Canada justifiably wanting to change up several elements.
It has shades of the Browns’ Freddie Kitchens/Todd Monken experiment. And we know Canada didn’t last long in LSU due to something between him and Ed Orgeron. But that he’s even in the building is a positive. The Steelers offense needs more creativity, less predictability, and a stronger desire to take advantage of the free efficiency that exists in today’s offensive game.
After all, the Steelers play in the AFC North with one of the most analytically advanced teams in the NFL. Every intentional move away from efficiency is magnified when a team like the Ravens stand between you and the crown of King of the North.
Coaching will be extremely important because, for the second straight year, the Steelers have the NFL’s cheapest skill position corps. They literally are spending the 32nd-highest cap hit on wide receivers and 32nd-highest cap hit on running backs in 2020. That means youth and inexperience.
In addition to the hope of coaching improvement, another positive is the schedule for Roethlisberger. He missed 2019 when the Steelers played the ninth-toughest schedule of pass defenses. But in 2020, I forecast the Steelers will face the second-easiest schedule of pass defenses. That drop in difficulty, from ninth to 31st, is the third-largest for any team.
After facing the 15th-toughest overall schedule in 2019 the Steelers will face the seventh-easiest in 2020. That increase is the sixth-best improvement for any team. Pittsburgh gets to play seven games against teams forecast to win 7.5 or fewer games on the season.
Their 2019 schedule started off with three games against playoff teams, two of which were on the road (Patriots, Seahawks, and 49ers). They lost Roethlisberger in the second game and the season was over before it started. But in 2020, the Steelers are one of three teams to start the season’s first three weeks against three opponents that are all forecast to produce a losing record in 2020 (Giants, Broncos, and Texans).
In their shift from the ninth-toughest schedule of pass defenses to the second-easiest, they play just three games against top-15 pass defenses. They played seven games against top-15 pass defenses in 2019.
Pittsburgh's schedule is also favorable in several other ways. Although they play in two Monday night games, they get to host the following game each time, negating a short week road game. Their Week 2 opponent, the Broncos, will be playing on a short week road game being they play on Monday in Week 1. Pittsburgh has a bye ahead of their second-toughest road game (Week 9 in Dallas). The Steelers host the Ravens on Thanksgiving. And after a Sunday night tilt on the road in Buffalo, they have one extra day to prepare for their Monday game in Cincinnati. They play zero back-to-back road games other than that one game the entire season, and they have extra rest for that game.
