---
title: Carolina Panthers
author: ''
date: '2020-09-04'
slug: carolina-panthers
categories: []
tags: []
---

There are some situations you can see from a mile away that have very little hope. The 2019 Panthers struggling to have success after Cam Newton was done for the season was one of those situations.
Make no mistake – they battled admirably, but this was not a winnable battle.
Teams are built with identities. The Cam Newton-led Panthers had an identity. Before Norv and Scott Turner called plays, the way to beat the Panthers was to stop Newton’s legs. If you couldn’t take his wheels out, it’s unlikely you would win. The Turners took Newton’s passing to another, more efficient level, to prevent a team from dominating just by slowing down the quarterback on the ground. But Newton’s wheels were still a consistent part of the offense’s productivity.
Whether it’s Cam Newton running or the threat of his running, defenses frequently needed to allocate extra defenders to stop the dynamic quarterback. Defenses didn’t have to do anything close when Cam’s 2019 replacement, Kyle Allen, stepped into the huddle.
In Newton’s last year, he recorded a 55% rushing success rate with 5.7 YPC. He had 40 designed runs on the season. But he was also great knowing when to keep the ball due to coverage or simply open run lanes when he dropped back on a pass play.
Through Week 11 of 2019, Allen had a total of just nine rushing attempts and only one was successful (2.9 YPC). He had two designed runs, which averaged 1.0 YPC and a 0% success rate. He didn’t even attempt a single run when presented with an open run lane on a pass play.

with Newton because Allen wasn’t close to the dual-threat Cam Newton was, even in his last year in Carolina.
It is important to remember that Newton injured his foot in the 2019 preseason game against the Patriots and was never right after that. He wasn’t healthy Week 1 or Week 2. It wasn’t his shoulder injury that caused problems the previous season. The issue in 2019 was his foot and how that injury was handled. And as I mentioned at the top, the key to taking out Cam for years has been to take out his wheels.
With a hobbled Newton, the Panthers lost the first two games of the season, but won the Early Down Success Rate (EDSR) battle in both. EDSR has proven to be the most correlated metric to wins behind only turnover margin. But the problem for the Panthers was they lost the turnover battle in both of those first two games of the season, and that was the driver in losing both games by less than a touchdown each game.
The 2019 Panthers started the season out 1-2 but went 3-0 in the EDSR battle. However, from Week 4 onward, the Panthers lost the EDSR battle in 10 of 13 games. They narrowly won the EDSR battle in Week 10 in Green Bay and Week 15 against Seattle, but lost both by one score after losing the turnover battle in each game.
Remarkably, despite a 5-11 record, the Panthers ranked ninth in overall EDSR offensively. Their problem was third down offense, which ranked 29th, and overall offensive efficiency, which ranked 28th.
Taking a young quarterback and getting him to perform as well as the Panthers did on first down speaks volumes regarding the Turners when calling the offense. Kyle Allen recorded 8.2 YPA on first down, which ranked eighth-best in the NFL, slotting in right behind Patrick Mahomes (8.5 YPA). Allen’s other first down passing metrics (EPA, success rate, and rating) all ranked above league average.
Even without play-action on first down, Allen was still very productive. Of his 176 first down attempts, 102 came without play-action.
Allen was extremely well-coached and knew where to go with the ball more frequently on first down. He threw just one interception on first down all season, posting a 0.5% interception rate.
The problem was after first down.
His 0.5% interception rate ballooned to 4.2% on second down and 5.1% on third down. His EPA, YPA, and passer rating dipped to well below average marks by the time the Panthers reached second and third down.
Allen posted the NFL’s worst YPA and passer rating on third down passes. He also took 19 sacks for a whopping 158 yards, the second-most yards lost in the NFL.

The more he had to react to the defense, such as on third down when in obvious passing situations, the worse he played. Allen’s efficiency on early downs, led by first down, compared to third down is visually depicted in the completion percentage by depth graphic in this chapter.
Some coaches may have been leery of starting an inexperienced quarterback and chosen to play things slightly more conservatively on first down. But the Panthers passed the ball on 54% of first downs, the fifth-highest rate in the NFL (average was 48% pass). But unlike a team like the Dolphins, who passed a lot on first down once trailing in the second half, the Panthers opened the game by passing on first down. In the first half, Carolina passed the ball on 55% of first downs, fifth-highest in the NFL.
Some coaches would want to let a stud running back like Christian McCaffrey carry more of the load in the first half with an inexperienced quarterback. It was smart the Panthers did not: on first downs, McCaffrey averaged 4.8 YPC and posted a 47% success rate. His EPA, yards/play, and success rate were all lower than when Allen dropped back to pass.
Running more often on first down would have made the Panthers even less likely to win games. The fact the Turners operated in this manner bodes well for the Redskins with young Dwayne Haskins behind center.
Aside from intelligently using a smart pass:run ratio on first down and coaching up Allen on where to pass on those plays, the Panthers offense was smart in many other areas.
First, they used the fifth most play-action on early downs in the game’s first three quarters. This was massive because Allen’s splits with and without play-action were large, particularly on second down.

Second, the Panthers used the sixth-most pre-snap motion in the game’s first three quarters. They recorded the seventh-highest increase in efficiency when using pre-snap motion ahead of passing plays. Carolina also had the second-most pre-snap motion ahead of run plays. Such motion generated the fourth-best improvement in rushing efficiency in the NFL.
Although it is tough with a young quarterback, the Panthers could have chosen to give him more of an ability to check out of run plays when faced with a stacked box. When faced with 8+ men in the box on early downs in the game’s first three quarters, the Panthers still went 63% run. This was slightly below league average (65%) but the splits were large for Carolina.
Runs into these stacked boxes generated a 43% success rate and only 3.9 YPC, while passes from Allen generated 8.6 YPA with a 54% success rate, both being slightly above average.
The majority of these runs came when the offense was in 12 personnel. There may have been opportunities available to check to more passing plays when in 12, because that was a grouping Allen excelled in, particularly when the box was stacked.
When passing out of 12 against stacked boxes Allen delivered 11.8 YPA and a 61% success rate.
One of the most interesting factors in the Panthers’ 2019 season was the difference in production in the red zone after halftime. In the first half of games, their success rate was 53% inside the red zone on all plays. They were one of four teams to average over a 50% success rate in the red zone. The others all made the playoffs (Ravens, Titans, and Packers).
But in the second half, their red zone play success rate dropped to 37%. They were one of four teams to record a sub-38% success rate in the second half of games.
A big reason was the 2-back sets drying up in productivity. In the first half, with 2-backs the Panthers produced an 82% play success rate. They ran the ball on 64% of these plays and delivered a 100% rushing success rate. But in the second half, the Panthers’ 82% success rate dropped to just 13%. They went 87% run on these second half red zone plays with 2-backs on the field, and these runs recorded just a 15% success rate.

It will be extremely interesting to see the new team philosophy now that Matt Rhule gets his first shot as an NFL head coach. He has ample experience with rebuilds in college coaching tops at Temple and Baylor and appears he will get his first chance to do so in Carolina. The laundry list of players eliminated from the Panthers is extensive.
The team will now be led by Teddy Bridgewater and the offense directed by offensive coordinator Joe Brady of LSU fame. Bridgewater has the most insane ATS mark for a quarterback in history. He has led his teams to a 31-9 ATS (78%) record in games where he has attempted at least one pass. His teams are 25-15 straight up (63%) during that span since 2014. He had to fill in for Drew Brees with the Saints last year and went 6-0 SU and ATS as a starter.
If you want to look to give some of that credit to Sean Payton, as some might, I’ll point you back to 2015, his last full season in Minnesota, where the team went 11-6 SU and 14-3 (82%) ATS. This was a team coordinated by Norv Turner. They were projected to win just 8 games in 2015 and clearly hit that over.
On every team Bridgewater played and started games, they hit the over on their win total. A perfect 4-0 in seasons his teams exceeded their projected win totals. He is nowhere near as flashy as Cam Newton, but he has been a proven winner, although considerably overlooked.
The rebuild offensively goes beyond just the quarterback and offensive coordinator. The Panthers return only three of five starters on the offensive line from 2019. But consider the context of their 2019 line, which was the third-most inexpensive line in the NFL (only $22.6M in cap). The 2020 line commands $39.8M in cap space and is right around league average (18th in cap allocation).
The Panthers have their primary wide receivers back and added Robby Anderson to the mix. D.J. Moore was excellent in 2019, but the opposite was true for Curtis Samuel and it’s interesting to see the splits in Samuel’s performance.
Samuel was tremendous when playing in 12 or 21 personnel, where he produced 9.4 YPA and a 63% success rate when targeted, with an aDOT of 14.4 yards. But 74 of his 104 targets came in 11 personnel, and he was terrible in 11. Of these targets, it didn’t matter whether he aligned out wide or in the slot. He recorded just 4.5 YPA and a 35% success rate. In 2018, Samuel was productive out wide in 11, but struggled from the slot. In his career, in the slot from 11 he averaged just 5.2 YPA and a 41% success rate, both much lower than out wide in 11 or in 12 or 21 personnel.

With Cam Newton playing just two games in 2019, the Panthers were forced to lean on Kyle Allen to carry the offense before taking a late-season look at Will Grier. The results of their quarterback situation were not pretty as Carolina closed the 2019 season ranked respectably 15th in success rate through the air (45%), but ended up 29th in EPA via their passing offense, 29th in yards per pass attempt (6.5 yards), and 30th in yards per passing play called (5.3 yards). The team has since moved on from Newton, releasing the longtime starter after nine seasons. Adding Joe Brady to run the offense and passing game, Carolina signed Teddy Bridgewater, who completed 67.9% of his passes for 7.1 Y/A with nine touchdowns and two interceptions in five games of relief for Drew Brees and the Saints a year ago. Bridgewater has not been a full-time starting quarterback since the 2015 season.

Due to their fluctuation at quarterback, Carolina ranked 30th in yards per pass attempt (6.9 yards) and 24th in success rate (49%) on throws to their wide receivers a year ago. Despite that, second-year wideout D.J. Moore took another step forward, catching 87-of-135 targets for 1,175 yards and four touchdowns. The team also added Robby Anderson in free agency to go alongside Moore and Curtis Samuel. Carolina ranked 24th in yards per attempt (6.6 yards) and 20th in success rate (51%) targeting their tight ends in 2019. Veteran Greg Olsen was also released this offseason, with Carolina turning the position over to Ian Thomas in his third season. With Christian McCaffrey out of the backfield, Carolina was NFL-best targeting RBs.

Even with Christian McCaffrey, the Carolina run game was not hyper-efficient a year ago. The Panthers ranked 22nd in success rate (45%) and 31st in yards to successful play rate, but because they were fourth in the league in rushing touchdowns (20) and eighth in yards above successful play rate, the team was able to end the season respectably at 13th in EPA via their rushing offense. McCaffrey continued to set new career-highs on the ground, rushing 287 times for 1,387 yards and 15 touchdowns after 336 carries for 1,533 yards and nine touchdowns combined over his first two seasons in the league. McCaffrey played a league-high 93% of his team snaps for running backs and handled a league-high 88.2% of his backfield touches. With questionable depth behind him, the Panthers need McCaffrey to remain on the field.

A Cocktail for Fantasy Production in Carolina
The Panthers are one of the more intriguing “bad” teams in the league this season for fantasy purposes. With the new staff of Matt Rhule and Joe Brady, Carolina is expected to run an open offseason that is predicated on getting the ball in space to their playmakers. Brady was with the Saints over the 2017-2018 seasons as an offensive assistant while Teddy Bridgewater served as a backup to Drew Brees and then was pivotal in the progression of Joe Burrow a year ago at LSU.
Bridgewater is highly accurate and surrounded by a group of players who can excel after the catch. Christian McCaffrey led the NFL in yards after the catch (1,019) a year ago and is the only running back to ever have back-to-back seasons with 100 receptions. Since entering the league in 2017, only Michael Thomas (378) and DeAndre Hopkins (315) have more receptions than McCaffrey (303). We just saw D.J. Moore survive subpar quarterback play, posting 87-1,175-4 on 135 targets in his second year at age 22. Moore has averaged 7.7 yards and 4.5 yards after the catch in his first two seasons in the league.
Custis Samuel’s year three take-off was grounded as just 59.2% of his targets deemed catchable in 2019, the lowest rate of any receiver with 100 targets on the season. Samuel was pigeonholed as a downfield target by the previous regime, but his profile coming out of college was more of Swiss Army Knife. Samuel’s depth of target has climbed from 9.4 yards as a rookie, up to 12.2 yards in 2018, and up to 14.8 yards a year ago. The offensive transition and the addition of Robby Anderson opens the door for Samuel to be used in his proper context.
Anderson himself has teased us with pockets of WR1 output in each of the past three years, averaging 14.8 yards per catch over his first four seasons in the league. His vertical game is not a direct overlap with the lack of aggressiveness of Bridgewater, but Bridgewater was well above the league baseline in downfield accuracy when he did let it fly. Just 7.1% of Bridgewater’s throws were 20-plus yards downfield, but his 57.1% completion rate on those throws was second in the league among all quarterbacks with over 100 dropbacks on the season.
Lastly, third-year tight end Ian Thomas finally is getting his chance to be a full-time player after two seasons playing behind and filling in for veteran Greg Olsen. In nine games without Olsen active over his two seasons in the league Thomas has caught 35-of-55 targets for 348 yards and three touchdowns on 16.6% of the team's targets. To top off the offensive fits for this new scheme, the Carolina offense is attached to a defense we anticipate to be near the bottom of the league in a division where everyone can score points. Carolina was already 31st in the NFL in points allowed and 23rd in yards per play allowed in 2019 and lost key contributors in Luke Kuechly, James Bradberry, Gerald McCoy, Mario Addison, Vernon Butler, and Bruce Irvin. Obviously McCaffrey is the consensus top pick this summer in fantasy drafts, and Moore is a top-15 wide receiver selection, but Bridgewater is an underrated QB2 option while Samuel, Anderson, and Thomas offer upside for the depth of fantasy benches.

No defense turned over more players than the Panthers did during the offseason. Every draft pick for the Panthers came on the defensive side of the ball.
Carolina had a deep rotation of interior defenders over the past few seasons and are down to just one left standing. At least they kept the good one. Still, Kawann Short just turned 31 years old in February. The seventh overall pick was used on Auburn interior defender Derrick Brown to slot next to short and Baylor’s Bravvion Roy was selected in the sixth round. Both should get plenty of playing time with little other depth at the position.
On the edge, Brian Burns was great in his rookie season and proved he should have been drafted higher than 16th. After a frustrating split in playing time last season, the Panthers have no choice but to make him the No. 1 edge rusher. Stephen Weatherly is a rotational player who will be forced to start with the lack of depth at the position. Second-round pick Yetur Gross-Matos is an athletic freak who will at least be the third man in the rotation. After a great All Or Nothing moment for Efe Obada following the 2018 season, he played 27% of the defensive snaps in 2019 with little impact.
Shaq Thompson remains an ideal modern linebacker and he’ll take a bigger role with the retirement of Luke Kuechly. Former Temple Owl Tahir Whitehead was brought in as a free agent and while he’s in line to be a starter, he has struggled to cover in previous NFL stops. There’s little quality behind them and only undrafted free agents were brought in at the position.
Even if James Bradberry didn’t leave in free agency, this would be a position group dying for more quality. Among 92 cornerbacks with at least 300 coverage snaps played last season, Donte Jackson ranked 72nd in Adjusted Yards allowed per coverage snap, which factors in touchdowns and interceptions. The Panthers got a late gift when Eli Apple’s agreement with the Raiders did not work out. Fourth-round pick Troy Pride should also play a role as an athletic high-upside corner.
You have to feel for Tre Boston. He’s been one of the league’s best single-high deep safeties in the league over the past few seasons but was never able to cash in on more than a one-year deal in free agency. Then he finally signs a three-year deal this offseason and this is the defense he gets stuck on. Juston Burris played well in limited time in the second half of the season with the Browns last year but like Carolina’s other positions, there’s little veteran quality behind the starters. The Panthers doubled up in the draft with Jeremy Chinn in the second round and XFL standout Kenny Robinson in the fifth.

The defense is being overhauled completely. It was the sixth-most expensive defense in 2019 and is now the fifth-least expensive in 2020. All seven draft picks are defensive players and they added multiple defensive players in a very active free agency period.
After facing the second-toughest schedule in 2019, the Panthers’ bad luck continues by facing the sixth-toughest schedule in 2020. With the Saints, Bucs, and Falcons in the division, it will be tough sledding, but their non-division schedule does them no favors either.
They also don’t have the benefit of an early bye week. Early bye weeks tend to help first-year coaches make adjustments, but the Panthers 2020 bye is the last one possible: Week 13.
For a team that went heavy on defense in the draft, their offense could use more weaponry and will face the fifth-toughest schedule of run defenses. The Panthers love passing to Christian McCaffrey and will certainly do the same in 2020, but an interesting note: last year the Panthers played five teams that ranked bottom-10 in RB-pass defense and they went 4-1 in those games (1-10 in their other 11 games). In 2020 they are projected to face just two teams that ranked bottom-10 in RB-pass defense: the Raiders Week 1 and Cardinals Week 4.
The Panthers have one of the worst situations of all teams with a brand new coaching staff. The head coach is working to impart his philosophy and culture. The defensive coordinator Phil Snow will take on a young, inexperienced defense. The offensive coordinator is installing a brand new system, and they have a new quarterback with zero chemistry with his receivers. It won’t be easy given this difficult and abbreviated offseason. But the Panthers are hoping their rebuild gets them on the right track sooner rather than later.



