---
title: Kansas City Chiefs
author: ''
date: '2020-09-04'
slug: kansas-city-chiefs
categories: []
tags: []
---


Patrick Mahomes is at the mic. You have one question you can ask him. Mine is simple: “How?”

As in, how the hell are you so damn great at football? How the hell are you capable of
doing the things you do?

The man is like Neo. He sees the matrix and no matter how many Mr. Andersons he’s up
against or how overwhelming the odds appear to be, he can get his team out of the jam.

If you ever get exactly a 10-point lead on Mahomes, run for the hills. In 2019, when
opposing teams led the Chiefs by 10 or more points at any point, Mahomes went 5-0.
That’s insane. This included erasing the 24-point deficit to the Texans in their first playoff
game (the largest deficit overcome in NFL playoff history), erasing a 10-point deficit to the
Titans the next week in the AFC Championship game, and erasing a 10-point deficit to
the 49ers in the Super Bowl.

Three playoff games. Three 10+ point deficits overcome.

How do you trail the 49ers by 10 points with less than nine minutes left in the Super Bowl, at your own 17-yard line, and end up winning by 11 points? The Chiefs scored 21 points on offense within five minutes in the fourth quarter of a Super Bowl!
With Mahomes and Andy Reid, this team has finished 12-4 in consecutive seasons and could have won back-to-back Super Bowls but for an offsides infraction in the 2018 AFC Championship game.

They are returning all five starting offensive linemen from 2019. In fact, they are returning all 11 starters on offense (although first-round draft pick running back Clyde Edwards-Helaire may end up taking over for Damien Williams at some point). Defensively, this unit returns 10 of 11 starters, with cornerback Kendall Fuller leaving for Washington. There are question marks surrounding the availability of cornerback Bashaud Breeland who is suspended for four-games but is appealing.
With those lone player starting roster modifications, this is a team that has three things going for it:
1. Won the Super Bowl last year
2. Return basically everyone
3. Coaching staff is intact
4. No other team can say the same
And if there ever is an offseason where it’s more vital than ever before to have continuity and chemistry, it’s this offseason from hell. We’ve seen starting quarterbacks play musical chairs this offseason.
There are 13 new offensive coordinators this season.
There are only eight play callers who have their quarterback entering their third year together or longer:
• Andy Reid with Patrick Mahomes
• Kyle Shanahan with Jimmy Garoppolo
• Brian Schottenheimer with Russell Wilson • Doug Pederson with Carson Wentz
• Sean Payton with Drew Brees
• Brian Daboll with Josh Allen
• Jon Gruden with Derek Carr
• Sean McVay with Jared Goff
How many of these eight do you think make the playoffs? Seems like a huge advantage in an offseason like the one we’re having. (And note I left Ben Roethlisberger off the list because he doesn’t actually have two years of experience with Randy Fichtner, but that is a technicality.)
It might look easy when you have the best quarterback in football, but the Chiefs do a number of things offensively to give themselves an even larger head start than most teams. And they are unique in a number of aspects.
First, their passing rate. Yes, they have the best quarterback in the NFL. They want to throw early and often. But they also know that passes offer higher +EV than do rushes (several times more) and they lean even further into them.

No team in the NFL passed the ball as often as the Chiefs in the game’s first three quarters, a 67% rate.
The Chiefs passed the ball on 65% of their first downs in the game’s first half. The NFL’s second-most pass-heavy team is way down at 55%. The NFL average is 48%.
The Chiefs are a full 10% higher than any other team, and almost 20% above the league average. In fact, the Chiefs’ pass rate on early downs in the first half is the second-highest of any team in the last 20 years.
Second, due to their pass-heavy nature, they dictate coverage. The Chiefs force you to use six-or-fewer men in the box and then make you pay.

On early downs in the game’s first three quarters, NFL defenses predominantly use six-or-fewer-man boxes on 44% of snaps and go to seven-man boxes on 39% of snaps. But against the Chiefs, teams go with a light box on 66% of snaps, by far the highest rate in the NFL, and 22% above average.
This might sound unimportant, but it’s extremely valuable: the Chiefs know what is coming. Nearly seven out of 10 snaps will be against a light box when you play them, whereas for most offenses it’s nearly a 50/50 proposition.
You might think logically that the time to run the ball is against a light box and you wouldn’t be wrong. Teams peak on EPA/carry and YPC when running on light boxes rather than neutral seven man boxes. Running on 8+ man boxes yields the worst EPA/carry and YPC in these early down situations.
And that was no different for the Chiefs:

• 6- man box runs: 5.3 YPC, -0.04 EPA/carry • 7 man box runs: 4.2 YPC, -0.15 EPA/carry
• 8+ man box runs: 1.9 YPC, -0.27 EPA/carry
However, for the Chiefs, they have the NFL’s best quarterback. So why gain 5.3 YPC with -0.04 EPA/carry when you can still pass on those light boxes and gain 8.5 YPA with 0.24 EPA/att? So, for that reason, the Chiefs kept throwing the ball in those situations (73% pass).
Third, what the Chiefs absolutely refuse to do is to run into heavy boxes on early down plays in the first three quarters. Their run rate when the defense was in an 8+ man box is the lowest in the NFL. The Chiefs won’t play into your hands – if you’ve got bodies in the box, they’re throwing. Sounds simple, but no other offense passes as often as the Chiefs.
Fourth, another thing that makes the Chiefs offense unique is that they don’t need to manufacture offense by use of play-action or pre-snap motion like many offenses.
On early downs in the game’s first three quarters, the NFL average is a 36% use of play-action. Across the league, play-action adds 0.14 EPA/att, 4% success, and 1.9 YPA compared to dropbacks without play-action. More teams should use play-action more often.
But without play-action, the Chiefs averaged 0.19 EPA/att and 57% success. Their EPA/att without play-action ranked third, as did their success rate. Play-action wasn’t needed because Mahomes is already so outstanding.
The same is true for pre-snap motion (PSM). In the game’s first three quarters, the NFL average is 40% PSM before passes. And PSM adds 0.02 EPA/att, 3% success, and 0.2 YPA compared to passes not using PSM.
But without PSM, the Chiefs averaged 0.25 EPA/att and 53% success. Their EPA/att without PSM ranked second and their success rate ranked fifth. In fact, the Chiefs were better from an EPA/att perspective without using PSM. Again, with a quarterback like Mahomes, it can make his job easier to use PSM, but it’s not a prerequisite for success like it is with most quarterbacks.
Andy Reid still uses the fifth-most PSM and the 10th-most play action, because it’s smart and some defenses are worse when it’s used, but Mahomes can still dominate on snaps without either.

Fifth, no team has a coach that schemes up as many easy options for the quarterback that will still provide efficiency like Andy Reid. Case in point, passes behind the line of scrimmage in opposing territory. Some coaches design nice passes on first down behind the line of scrimmage. So does Reid. But let’s look beyond that.
Passes thrown on second through fourth down behind the line of scrimmage don’t fare well in opposing territory. Sure, they’re easy completions. But they result in -0.10 EPA/att on average. The Chiefs gained 0.12 EPA/att on these passes, which ranked fourth in the NFL. And no team threw more of these passes than the Chiefs.
Reid could force Mahomes to use his arm talent to the max as often as possible and design a more high-leverage offense. Big hits but some big misses. Some huge wins but some bad losses. Instead, Reid has raised the floor of this offense completely. He makes life easy on an already great quarterback who doesn’t need life to be made easy, but certainly appreciates it.
Sixth, and lastly, Reid knows when to run the ball. Rushes inside the red zone generate 0.02 EPA/att and a 49% success rate while passes generate -0.07 EPA/att and a 41% success rate. Short yardage and in the red zone are two of the most desirable times to run, and in most other situations, passes will offer the highest upside for most teams.
I already mentioned how pass-heavy Reid is, the most pass heavy in the NFL by far. However, inside the red zone, the Chiefs throw the ball on only 52% of plays, which ranks 21st in frequency. They actually run the ball at an above average clip.
Not only is it smart from a league-average perspective, it’s smart for KC. Mahomes averaged 0.05 EPA/att and a 47% success rate in the red zone last year, but their red zone runs gained 0.15 EPA/att and a 56% success rate. This justifies Reid’s move to go run-heavy.
Looking at the other teams that ranked top-10 in pass rate in the first three quarters, only one other team aside from the Chiefs shifted to run the ball at an above average rate in the red zone. All of the other teams in the top-10 stayed pass-heavy. No team in the NFL shifted from as much full-field passing to as much rushing in the red zone as the Chiefs.
There are more than those six unique things that the Chiefs offense does, but those are examples. They’ve got a stud quarterback, a loaded roster, AND are aggressively pursuing non-conventional plans of attack which put them well outside the norm.
Coupled with the fact they use a lot of personnel grouping diversity and have a mobile quarterback who scrambles for first downs and doesn’t take sacks on third downs, this team will be just as capable of winning in 2020 as they were in 2019.

The Chiefs were right at the top of the league in passing output, even with Patrick Mahomes missing two and a half games due to injury. Kansas City ranked first in EPA via passing offense, second in yards per passing play (7.4 yards), and third in success rate passing (50%). With Mahomes having some natural regression off his stellar 2018 output, he managed to finish fourth in the league in yards per pass attempt (8.3), seventh in passing yardage per game (287.9), and eighth in touchdown rate (5.4%) during the regular season. Through 31 regular season starts, Mahomes ranks first all-time in passing touchdowns (76) and adjusted passing yards per attempt (9.2 AY/A), passing yardage (9,412 yards), and second in yards per pass attempt (8.6) only behind Kurt Warner (9.1). With the Chiefs returning 10 of 11 starters on the offensive side of the ball from their Super Bowl-winning roster a year ago, Mahomes is primed for another top-shelf campaign.

The Kansas City wideouts collectively ranked sixth in yards per target (9.3 yards) and eighth in success rate (54%). This season, the Chiefs are returning every receiver who took a snap for them last season outside of De’Anthony Thomas. Anchored by Travis Kelce at tight end, the Chiefs ranked second in success rate (62%) and fourth in yards per target (9.3 yards) targeting their tight ends. The one area where the Chiefs will look to improve is using their backs in the passing game more effectively. In 2019, they ranked 21st in success rate (43%) and 25th in yards per target (5.4 yards) targeting their backs. Rookie Clyde Edwards-Helaire recorded the most receptions for any drafted running back in his final season since DeMarco Murray.

Kansas City ran the least in neutral game script (39%) through the opening three-quarters of games. The Chiefs ranked 23rd in rushing yards per game (98.1 yards) and 20th in yards per carry (4.2 yards), but ran the ball situationally, which led to ranking fourth in the league in success rate (53%) and sixth in expected points added via rushing offense. In addition to retaining Damien Williams (who ranked 15th in success rate rushing at 52%), Edwards-Helaire will be a weapon on the ground. He handled 56.7% of the LSU non-QB rushing attempts in 2019, yet produced 65.2% of their rushing yardage. That +8.5% gap in yardage versus usage was tops in this draft class. His +2.0 yards per carry compared to his non-QB teammates was also first in this class.

Can Clyde Edwards-Helaire be a league winner?
No back raised their draft stock more during the 2019 season nor exited the draft with his fantasy stock elevated higher by landing spot than Edwards-Helaire. He benefited from playing in the highest-scoring offense in the country, but Edwards-Helaire also was hyper-efficient on his own merit as discussed in the rushing outlook portion of the team previously. That added context was for rushing only, he handled 56.7% of the team's non-QB rushing attempts, yet produced 65.2% of their rushing yardage. Edwards-Helaire led all backs in this class with 3.7 receptions per game in 2019 and ran 21% of routes split out as a receiver, the most in this draft class.
Often compared stylistically and physically to Brian Westbrook, Edwards-Helaire lands with attachment to Andy Reid, who provided the offensive propane for Westbrook’s fantasy career in which he was a top-10 fantasy back all five seasons 2004-2008. Through 16 years as a head coach or playcaller, Reid’s top running back has been a top-10 scorer 12 times. If Edwards-Helaire can dispatch Damien Williams quickly into the season, then the sky is the limit given his dual usage. Over his final seven full games played, Williams himself played 77% of the snaps, handled 82% of the backfield touches, and averaged 110.4 yards from scrimmage and 22.9 PPR points per game.
At 224 pounds compared to 207 for Edwards-Helaire, Williams still stands to be a potential thorn in goal-line situations. I would also take the under on Edwards-Helaire reaching the 325-touch mark Kareem Hunt had as a rookie in this offense in 2017 when he had 272 carries and the next closest running back (Charcandrick West) had just 18 carries. But if Edwards-Helaire can approach 250 touches, that may be all that he needs to crack being an RB1 as a rookie.
Can Mecole Hardman make a jump in year two?
With one of the league’s best offenses now for three years running, the Chiefs offense has been a major target for fantasy gamers. The entire core of their offense (Mahomes, Edwards-Helaire, Tyreek Hill, and Kelce) all come at the cost of high draft capital and are hard to obtain. With that, there are not a lot of value plays to be had within the offense. One of their less rich commodities is Hardman. As a rookie, Hardman led all players with 25 or more targets on the season in yards per reception (20.7), yards per target (13.1), and finished second in percentage of targets that resulted in a gain of 20 or more yards or a touchdown (36.6%). He also was third in the NFL in kickoff return yards, fifth in average per kickoff return (26.1 yards) with a touchdown.
Generating explosive plays is his game, but with the Chiefs returning 99.3% of their wide receiver targets from a year ago, can we realistically anticipate Hardman’s opportunity level to take off? In 13 games played with both Tyreek Hill and Sammy Watkins active, Hardman caught 12-of-18 targets for 248 yards and three touchdowns. In two of those games, Hill also only played 12 and seven snaps total. At the end of the day, Hardman is an upside pick you would like to have rostered in case of an expanded role or an injury due to his big play ability, but the overall opportunity in the offense may not match the opportunity of surrounding wide receivers at similar cost.

Kansas City was a team led by the offense but a defensive turnaround over the second half of the season helped propel the Super Bowl run.
If Chris Jones stays (he’s currently franchise tagged and has threatened a holdout) the Chiefs are fine because Jones is one of the league’s best interior linemen against both the pass and the run. He was second in pressure rate among defensive tackles per SIS and third in ESPN’s Pass Rush Win Rate. Derrick Nnadi and Mike Pennel were able to fill in during the few games Jones missed, but having Jones on the field is what makes this line special.
Frank Clark started the season terribly but improved as the year and his health progressed. Alex Okafor was fine as a rotational rusher but the Chiefs might miss Emannuel Ogbah, who led the team in pressure rate last season. Tanoh Kpassagnon was a big body out there but left a lot to be desired with his actual pass rushing. If Chris Jones does not play, Kpassagnon might be better served as an undersized interior defender. As a team, the Chiefs were just 19th in Pass Rush Win Rate.
The Chiefs played Dime+ on 33% of their defensive snaps, which was the sixth-highest rate in the league. They relied more on that as the season went on. In 2019, the linebacker wasn’t strong so the Chiefs limited the impact of the position. Kansas City gave a big deal to Anthony Hitchens before the 2018 season (and one they can’t get out of until 2021 after a restructure) but instead of forcing Hitchens to do things he wasn’t good at, they worked around him/Wilson/Ben Niemann — mostly with safeties taking coverage responsibilities. Kansas City took Willie Gay in the second round, a first-round talent who dropped in the draft for some off-field concerns.
The Chiefs wandered into a group of successful corners last season without much invested at the position. Charvarious Ward ranked 28th in Adjusted Yards allowed per coverage snap among 92 corners with at least 300 snaps in 2019 and Bashaud Breeland ranked 32nd. Rashad Fenton only played 115 coverage snaps per SIS, but his 0.38 AYa/CS figure ranked 11th among the 145 corners who hit 100, an impressive start for a sixth-round rookie.
There might not be a more versatile group of safeties in the league. To consider Tyrann Mathieu as a safety underplays the role he played last season when he was arguably the team’s best box safety, free safety, outside corner, slot corner, linebacker, and pass rusher on the lead up to the Super Bowl.
Daniel Sorensen played a de facto linebacker late in the season and while he has some flaws, he held up well enough at the position. Juan Thornhill was a rookie star at safety before a torn ACL ended his season at the end of December.
Outside of Gay, the Chiefs only added cornerbacks L’Jarius Sneed in the fourth round and Thakarius Keyes in the seventh round in the draft, among many other undrafted free agents. The core of this defense should remain mostly unchanged.

We see the highlight plays from Mahomes — the deep passes, the aggressive downfield style. But the way Reid has designed this offense, Mahomes was expected to complete 66.5% of his passes in 2019. We can measure that using player tracking data. We can calculate it based on factors such as receiver separation from the nearest defender, where the receiver is on the field and the separation the passer had at time of throw from the nearest pass rusher. That 66.5% rate was the fifth-highest in the NFL.
While there are absolutely those out of structure passes that Mahomes throws into tight coverage or while racing outside the pocket, about to be leveled, those stand out in our brain due to von Restorff effect. We see 50 Mahomes attempts, but the ones we remember are those that stand out. Mahomes is the best we have, but Reid tries to make his life easy and that, in turn, makes Mahomes even better.
Additionally, and defying your perceptions of Mahomes, he ranked just 36 out of 39 QBs in aggressiveness. Again, using player tracking data, aggressiveness tracks the amount of passing attempts a quarterback makes that are into tight coverage, where there is a defender within 1 yard of the receiver at the time of completion or incompletion. Mahomes’s rank in aggressiveness in both of his seasons as a full-time starter (2018 and 2019) has been 36 of 39 each year. Reid has designed an offense which gets players open and is far easier on his quarterback than Reid gets credit for.
The Chiefs were very interesting from an EDSR perspective. They dominated the first four weeks of the season and in their last five games before the Super Bowl. They went 9-0 in those games and also won the EDSR battle in eight of the nine (lone EDSR loss was Week 17).
Then, during the Week 5 Colts game that the Chiefs lost by six points, Patrick Mahomes suffered a high-ankle sprain. He was not 100% in the Week 6 one-score loss to the Texans or the Week 7 win over the Broncos. In that game against the Broncos, Mahomes dislocated his kneecap and missed Weeks 8 and 9. Mahomes returned at less than 100% in Week 10 to incur a three-point loss to the Titans. He then beat the Chargers in Mexico City, again at less than 100%, before the Chiefs had their bye week and he was able to heal up.
There was a stretch of seven games, from Week 5 through 11, where Mahomes was either not 100% due to various injuries, or not there altogether. The Chiefs offense suffered for it, winning the EDSR battle in only two of seven games, and losing outright in four of the seven games.
The Chiefs held a huge lead early against the Raiders coming out of the bye (thus explaining the narrow ESDR loss). And they followed that up by performing extremely well in the first half in Foxboro against the Patriots (led 20-7 at halftime) before Mahomes banged his throwing hand causing swelling and the team had to alter the second half game plan entirely.
In games Mahomes was healthy and did not suffer an in-game injury, the Chiefs went 9-0 in 2019, 8-1 in the EDSR battle, and won these games by 14 ppg on average.
Their offense ranked third in EDSR and they face a similar slate of defenses in 202 (19th-toughest schedule).
So how do you beat these guys? How do you knock off the Chiefs?
Well, for one, you must score. They are 27-8 the last two years with Mahomes at the helm, and when Mahomes was not playing injured, his team has scored at least 28 points in all losses. The Chiefs average 36 ppg in his losses at full health. Opponents have to average 39 ppg to beat him. So first thing is first, you have to score.
There are several ways to do that defensively. The Chiefs defense ranked just 24th in EDSR last season and was 14th in efficiency. They are highly susceptible to play-action, particularly play-action under center. They are similarly highly susceptible to pre-snap motion, particularly when offenses use it ahead of run plays. They ranked second in pressure and sacks on third down, but when offenses passed on early downs, the Chiefs had one of the NFL’s worst sack and pressure rates in the NFL. Additionally, while the Chiefs had the sixth-ranked pass defense, they struggled to defend passes between the numbers, particularly on early downs, ranked 30th in the NFL. The defending Super Bowl champions won it all last year against the 15th easiest schedule. In 2020, they face the 10th-easiest schedule based on opponent win totals, and it’s especially easier in one area: opposing rush offenses.
The Chiefs struggled to stop the run last year and actually went 1-4 in the regular season against teams with top-12 rushing attacks. They went 11-0 against all other opponents. Their 2019 schedule of rushing attacks faced ranked 14th easiest. In 2020, it improves to fourth-easiest. They still face four teams with rushing attacks that rank top-12 (Texans, Ravens, Panthers and Saints) but on average, their overall schedule is much easier.
The least fortunate aspect to the Chiefs schedule is the location of their toughest games. The Chiefs play four teams projected (after incorporating juice) to win 9+ games, and all four are on the road (Ravens, Bills, Buccaneers, and Saints). The first of these games is Monday night, in Baltimore. Shockingly, the Ravens have played in 14 Monday night games since 2008 but only two were at home, so this year will be the third. The Chiefs also must travel to Buffalo to play on a short-week Thursday game.
Between Week 7 and 17, the Chiefs face the easiest schedule in the NFL, and are fortunate to play eight of 10 teams that are forecast to post at-or-below .500 records. The two difficult teams they face are both from the NFC South (Buccaneers and Saints) and both come as the second of back-to-back road tilts.
