---
title: Philadelphia Eagles
author: ''
date: '2020-09-04'
slug: philadelphia-eagles
categories: []
tags: []
---

When the Eagles won the 2017 Super Bowl, they had Zach Ertz healthy for all but two games, and their three starting wide receivers didn’t miss a regular season start (Alshon Jeffery, Nelson Agholor, and Torrey Smith)
 
Their top four receivers in receptions in 2017 were their No. 1 tight end and their top three
wide receivers. Very standard and very reliable.

The speed of Smith (4.36 40-time) was something the Eagles wanted to replicate the
following year after they traded him to Carolina. So, in 2018 they signed 4.33 40-time .Mike Wallace to a one-year deal. But in Week 2 of the 2018 season, Wallace fractured
his fibula and was lost for the season. He finished the 2018 season with zero receptions
on three targets. Jeffery missed the first three weeks of the season recovering from .offseason rotator cuff surgery he received after the Super Bowl.
Without two of their top-3 wide receivers for the first three weeks of the season, and with
Carson Wentz recovering from ACL surgery, the Eagles were down to targeting
receivers like Josh Perkins, Kamar Aiken, DeAndre Carter, and Shelton Gibson. It wasn’t
pretty. Later in the season, with Agholor struggling, still no sign of Mike Wallace and the
Eagles down to very little WR talent behind Jeffery, they acquired Golden Tate at the trade deadline.

Their top four receivers in receptions in 2018 were their top tight end, top-2 wide receivers, and their newly drafted rookie tight end, Dallas Goedert.
And let’s not forget how that season ended: a trip to the playoffs, a Wild Card round win in Chicago, and a game in New Orleans in the Divisional Round that saw the Eagles down six points (20-14) with the ball on the Saints 27-yard line, on 2nd and 10, with 2:01 left in the game. Nick Foles threw a perfect pass to Jeffery which went right through his hands, was intercepted, and the Saints advanced to the Championship game. If Jeffery doesn’t drop the ball, the Eagles may score and win that game, face the Rams (who they had already beaten 30-23 in Week 15), and then would have faced the Patriots in the Super Bowl for the second time in two years.
The negativity of the way the 2018 season ended was replaced with optimism at the start of 2019 due to player health and player acquisitions, specifically at the quarterback and receiver positions.

General manager Howie Roseman brought home DeSean Jackson. Jackson started his career with the Eagles and played the prior two seasons with the Buccaneers. He still had the deep threat potential and displayed it often in Tampa, averaging 18.9 yards per reception, his third-highest average of his 11-year career.
Jackson’s speed was going to give the Eagles that deep threat they missed in 2018, along with far more ball skills and ability to gain YAC than what they had in their 2017 deep threat, Smith. Jackson played double-digit games in 10 of his 11 years in the NFL and was extremely healthy in general for a 32-year old deep threat receiver.
The season was looking extremely promising. Starting quarterback Carson Wentz wasn’t off season-ending surgery and was able to play all offseason and Week 1, unlike 2018. No. 1 receiver Jeffery wasn’t off offseason surgery and would be fully healthy in Week 1. They had their new speed burner No. 2 WR DeSean Jackson, and they would use Nelson Agholor in the slot. When they went to 2-WR sets, they could be extremely dangerous with Ertz, Goedert, Jeffrey, and Jackson on the field together. The Eagles also used a second-round pick on JJ Arcega-Whiteside out of Stanford. Arcega-Whiteside was a solid red zone threat and would have the ability to grow into his role, given the receiving talent ahead of him.
The Eagles had all their talent in Week 1 and everything went according to plan. Targets and production for Week 1:
Jackson: 9 targets, 8 receptions, 154 yards, 2 TDs Jeffery: 7 targets, 5 receptions, 49 yards, 1 TD Ertz: 7 targets, 5 receptions, 54 yards
Agholor: 5 targets, 2 receptions, 11 yards Goedert: 3 targets, 2 receptions, 16 yards
The rest of the targets went to running backs. They didn’t have to use any other receiver depth, JJAW could learn by watching, and the starting crew began to develop some chemistry together. Wentz passed for 313 yards and three touchdowns, was sacked just once, and though the game was a narrow win, it was a win.
Week 2 came on Sunday Night Football and it was time for the Eagles to unleash this passing attack for a second week in a row.

But early in the game, disaster struck.
  2019 Offensive Advanced Metrics
184 9101 5 11 5
(cont'd - see PHI-3) 2019 Defensive Advanced Metrics
• Dallas Goedert hurt his calf in pregame warmups and missed the game. One player unable to play on the 53-man active roster, and key player at that (41 snaps in Week 1), and the game hadn’t even started.
• On his sixth snap of the game, Alshon Jeffery also hurt his calf, and he was lost for the rest of the game.
• On his 11th snap of the game, DeSean Jackson hurt his groin, and he was lost for the rest of the game.
Just 11 snaps into the game, still early in the first quarter, and the Eagles were without their No. 1 receiver, No. 2 receiver, and No. 2 tight end. Making matters worse, No. 3 receiver Nelson Agholor had to leave the game to get a concussion test and missed some time.

Due to the demands of the 53-man roster, teams that play a lot of 2-TE sets don’t just have seven wide receivers active. So when your top three receivers are out, you’re in trouble. At one point, the Eagles were down to just two healthy receivers (Mack Hollins and Arcega-Whiteside) and one healthy tight end (Ertz).
It’s just Week 2 of the season, and a team isn’t even able to run 11 personnel because they literally don’t have three wide receivers. And that wouldn’t be the last time of the season the Eagles were unable to use 11 personnel in a game due to receiver health.
Ironically, if Agholor catches a perfect ball from Wentz down the sideline, down 24-20 with less than two minutes left, he has a walk-in touchdown and the Eagles likely win the game. Instead, they lose by the same score, 24-20.
The injury bug dug deep into the Eagles’ receiving corps for the second straight year in that Week 2 game and didn’t ever leave.

Jackson would be lost for the season. He tried to come back in Week 9, played four snaps, and was done. Jeffery missed the Week 3 game against the Lions. Once again, the Eagles were left resorting to target players like Mack Hollins seven times and playing rookie Arcega-Whiteside for a significant number of snaps.
Jeffery returned Week 4, but missed two more games in the middle of the season (narrow, one-score losses to the Patriots and Seahawks) before playing one more full game the rest of the season and re-injuring himself and landing on IR (Lisfranc injury).
If you’re tracking at home, that’s the Eagles’ No. 1 and No. 2 receivers down. And then came the injury to Nelson Agholor, who, though he had reliability issues, didn’t have availability issues until Week 12. He, too, missed the game against the Seahawks. He, too, played in one more full game after that. He, too, missed the rest of the season (knee).
From Week 2-17, the Eagles were without their No. 2 WR (speed threat Jackson). From Week 12 through the end of the season (save for Week 13), the Eagles were without their No. 1, No. 2, and No. 3 receivers.
Yet this team still swept their final four games and made the playoffs again. They found a way to win. But it wasn’t pretty nor was it easy.
The Eagles were forced to start Arcega-Whiteside, although he didn’t impress. They were forced to sign Greg Ward Jr. to the active roster for that Week 12 game where they first lost all their top receivers. Ward was an undrafted rookie who was a college quarterback that converted to wide receiver. He eventually became the team’s No. 1 receiver, that’s how crazy the end of the season got in Philadelphia.
Their top four receivers in receptions in 2018 were their No. 1 tight end, No. 2 tight end, No. 1 running back, and former No. 1 receiver who essentially missed half the team’s games (8) yet he still finished fourth in receptions thanks to injuries to the other receivers and lack of depth/talent at the position.
Someone find me another team in NFL history whose top three receivers in a season were two tight ends and a running back. I’ll wait.
The Eagles have ranked as one of the most-injured receiving corps over the last two years. It’s important to lay out the entire timeline of the Eagles receiver health struggles, particularly in 2019. Because most people look at stats without context and draw big conclusions from them.
And they’ll look at Wentz’s stats the last two years, and more importantly in 2019, and think that he struggled... that he’s not a great quarterback... that he might be regressing. That couldn’t be farther from the truth. Wentz excelled last season in crunch time. He excelled in the clutch. He had to play with a different group of inexperienced receivers every single week the entire second half of the season.
Despite those impediments, Wentz was excellent out of structure. You would think chemistry and rapport with receivers would be paramount for producing out of structure, and Wentz had neither.
The NFL average for quarterbacks shuffling when passing is a 41% success rate and -0.01 EPA/att. Wentz recorded a 55% success rate when shuffling, first in the NFL. His 0.31 EPA/att was also first in the NFL.
The NFL average for QBs that are moving when passing is a 42% success rate and 0.01 EPA/att. Wentz recorded a 55% success rate when moving, #1 in the NFL. His 0.32 EPA/att was also first in the NFL.
The Eagles are hopeful that the third time's a charm, and they will have better luck with receiver health in 2020. The team still has Alshon Jeffery and DeSean Jackson on the roster this season. But both are off of those season-ending injuries. The Eagles are hopeful both will be healthy and productive to start the season, but as we’ve seen, there’s absolutely no guarantee. As such, the Eagles decided to go with redundancy at the position.
They drafted TCU receiver Jalen Reagor in the first round. At 5’11” and 206 pounds at the combine, Reagor notched an amazing 98th percentile explosion score and a strong 66th percentile speed score (with a 4.47 40-time). They also traded for Marquise Goodwin, who ran a 4.27 40-time. Their hope is Jackson is healthy all season, but with Agholor finally gone (Raiders), the hope is that Reagor, Jackson, and Goodwin can provide the speed they need at the position. They didn’t stop there and added Boise State receiver John Hightower, who ran a 4.43 40-time, in the fifth round and Southern Miss receiver Quez Watkins, who ran a 4.35, in the sixth round.
Jeffery isn’t a speed threat at all, but the Eagles definitely now have some receivers that can use their speed. That is important, considering tight ends Ertz and Goedert were their leading receivers in 2019 and don’t have that type of speed.
The Eagles have a lot of offensive line turnover, and it didn’t help that right guard Brandon Brooks tore his Achilles tendon this offseason. Brandon Brooks allowed 0.75 sacks per year in four years in Philly. He was a three-time Pro Bowler the last three years and graded first, third, and sixth among all guards per PFF in those The Eagles passing game ranked 13th in the NFL success rate (47%), but ranked 16th in EPA and 26th in yards per pass attempt (6.6 yards). Considering all of the team injuries and their top two targets being tight ends, things could have been worse. It was also a testament to Carson Wentz playing better than his numbers, based on working with a skeleton crew of playmakers. Wentz played in all 16 games for the first time since his rookie season and has now had an interception rate below 2.0% in each of the past three seasons. They drafted Jalen Hurts in the second round this offseason to insure Wentz while simultaneously offering new wrinkles in the offense.

Given all of their injuries at wide receiver a year ago, the Eagles’ top two targets were Zach Ertz and Dallas Goedert. Ertz has always been a target magnet, but the team was forced to heavily lean on their tight ends to carry the passing game. Philadelphia used 12 personnel on a league-high 51% of their passing plays. The downside is that while they ranked first in tight end targets, they ranked 13th in success rate (55%) and 19th in yards per target (7.0) when throwing to their tight ends. At wide receiver, they were 32nd in yards per target (6.5). Bringing back older vets DeSean Jackson and Alshon Jeffery, the team went and added Jalen Reagor, Marquise Goodwin, John Hightower, and Quez Watkins this offseason.

The Eagles ranked 11th in the league in rushing yardage per game, 11 in success rate (49%), and 15th in EPA via their rushing offense in 2019. Moving forward in 2020, the team will now feature second-year back Miles Sanders, who they selected in the second round (no. 57 overall) a year ago. Sanders set a franchise rookie record with 1,327 yards from scrimmage. He rushed for 4.6 yards per carry, but ranked 34th out of 44 backs with 100 or more carries in success rate (45%). Behind Sanders, Boston Scott has an inline to maintain the role he had to close the season playing next to Sanders. Scott totaled 61 touches for 350 yards and four touchdowns over the final four games of the regular season. The depth of Scott, Corey Clement, Elijah Holyfield, and undrafted rookies Michael Warren and Adrian Killins is unsettled at this point of summer.

Is Miles Sanders ready to be an RB1?
Miles Sanders set a franchise rookie record with 1,327 yards from scrimmage in 2019, but did not play more than 53% of the team snaps in a game until Week 11. He averaged 18.5 touches for 95.4 yards per game over the final eight games of the season while playing 72% of the snaps. That includes two games against the Giants in which he dealt with dehydration (57% of the snaps) and left early due to injury (31%). From Weeks 11-16, Sanders scored the third-most PPR fantasy points in the league, behind Christian McCaffrey and Ezekiel Elliott over that span as he helped owners win fantasy titles.
The Eagles had a plethora of injuries to close the 2019 season, so it was unclear just how much the team is actually willing to go in on Sanders without tangible competition for lead opportunities. The real question is does head coach Doug Pederson prefer a committee of running backs or has he been forced to use a committee given what he has had to work with?
Sanders was the first back to receive 200 touches in a season for the Eagles since Pederson took over in 2016. Over those four seasons, an Eagles back has reached 20 touches in just 12 games, but Sanders accounted for three of those during his hot run to end the season. But Philadelphia had a consistent stable of compartmentalized backs over that span.
They have had passing-game first backs in Darren Sproles, Wendell Smallwood, and Corey Clement to go along with isolated running-game usage backs in LeGarrette Blount, Jordan Howard, Josh Adams, and Jay Ajayi. The closest back the Eagles had with three-down acumen under Pederson is Ryan Mathews, who was there for his final season in the NFL after suffering a herniated disc and having neck surgery.
That is the difference here with Sanders entering 2020. Sanders was a solid addition in the passing game, catching 50-of-63 targets for 509 yards and three touchdowns, becoming just one of two backs to average at least 10.0 yards per reception with over 40 catches last season. Sanders ranked eighth among all running backs in air yards despite ranking 13th in overall targets. While it may be true that Sanders never gets to 300-plus touches under Pederson, if he can turn his 229 touches a year ago into 250-270 touches with his dual usage ability, that is in the strike zone as a top-15 back with the upside if given even more opportunity.

The Eagles went about their defense this offseason with the strategy of “what if we just go a whole bunch of good players?” It worked.
Putting Javon Hargrave next to Fletcher Cox is unfair and will give nightmares to opposing guards and centers. Malik Jackson got into just one game last season but will now serve as a rotational piece, which still means the Eagles will lose little pass rush ability when either Cox or Hargrave comes off the field.
The Eagles also have one of the deepest edge rotations, even with the loss of Vinny Curry, who led the team in pressure rate with a rotational role. Last season, Brandon Graham and Derek Barnett took most of the defensive snaps (76% and 68%, respectively) and that will likely continue in 2020. Josh Sweat’s role will increase and he was the second-most productive edge rusher on the team by pressure rate last season. Genard Avery could also see a bigger role after a midseason trade from Cleveland.
Nate Gerry is fine in the middle of the defense but this is one place the Eagles could use an upgrade. They cut loose L.J. Fort early last season and he’d be the team’s best linebacker if on the roster. While the Eagles stacked up at other positions, Philadelphia’s addition to the group was a reserve linebacker from a team that barely played linebackers to begin with. Because there’s no depth, third-round pick Davion Taylor is likely to see the field early.
Entering the offseason, corner was the weakest spot on the Eagles’ roster but that made a concerted effort to fix that. They traded for Darius Slay, which gives them a true No.1 corner they haven’t had in years (Ronald Darby was one of the league’s worst corners in Adjusted Yards allowed per coverage snap) and the signing of Nickell Robey-Coleman to man the slot was one of the best deals of the offseason. There’s still a question about the second outside corner but there are a few bodies for that competition.
The loss of Malcolm Jenkins will hurt most at safety. He was one of the best players on the defense and was on the field for 99% of the defensive snaps in 2019. Converted corner Jalen Mills could be in line to potentially start next to Rodney McLeod, but there’s a reason Mills is converting from a position he struggled to play. Fourth-round pick K’Von Wallace has that slot-safety experience and could start immediately.

seasons. Left tackle Jason Peters was allowed to see his contract expire as 2019 first-round pick Andre Dillard, who struggled in 2019, will slot in as the starting left tackle. Left guard, center, and right tackle stay consistent, but the line will need to stay healthy and play well if the Eagles want to make another deep postseason run.
While the injury situation at the wide receiver position was a disaster, one thing that definitely went their way was the schedule. The Eagles played the NFL’s second-easiest schedule of pass defenses and fourth-easiest schedule of pass rushes.
Philadelphia played six opponents ranked top-15 in pass defense in 2019 and went 3-3 in these games. They are set to play seven such opponents next season and have two brutal stretches where they play three-straight teams with top-15 pass defenses from 2019 (49ers, Steelers, and Ravens in Weeks 4-6 and then Seahawks, Packers, and Saints Weeks 12-14).
After playing the 29th-toughest schedule of pass rushes, the Eagles face the second-toughest schedule in 2020. It’s the largest jump in difficulty in the NFL. That being said, playing weaker pass rushes didn’t help the Eagles in 2019. They played five games against bottom-5 pass rushes (Dolphins, Lions, Seahawks, and Falcons) if you count the playoff game and went 0-5 in those games. Looking purely at player tracking based Pass Rush Win Rate, the Falcons did rank second in the NFL, but didn’t hit home enough, but the rest of those four teams all ranked in the bottom half of the NFL, with the Lions and Dolphins pulling up at 31st and 32nd.
On the ground, the Eagles seem to be in a great spot with Miles Sanders. The Eagles have been looking for a running back to carry more of a load, but didn’t have good luck in years past. The Eagles traded for LeGarrette Blount prior to the 2017 season and traded for Jay Ajayi during the 2017 season (after Darren Sproles was lost for the year). They rode both to a Super Bowl title.
Sproles was in and out of the lineup with injuries in the 2018 and 2019 season. Jay Ajayi tore his ACL in 2018 in Week 5, so the Eagles were without their top two running backs for much of the 2018 season. They added Jordan Howard via a trade with the Bears last season, and while he was productive in spots early, he suffered a shoulder injury and was lost after Week 9.
The Eagles turned to Sanders as a rookie and he came up great, showing tremendous explosiveness on the ground. He also proved to be a dangerous receiver out of the backfield. For the first time in a couple of seasons, the Eagles didn’t trade for a running back (instead, they traded away Howard). They didn’t draft one, either. The backfield is firmly Sanders. The team still has a stable of receiving backs plus the shifty Boston Scott who showed a nose for the end zone and a solid early down success rate, but so long as Sanders can stay healthy, it’s hard to envision him not owning the lion share of touches.
While the Eagles are hoping for improved health, they can actively make several modifications to improve their success. One thing they can study is drop depth by Carson Wentz.
For whatever reason the last two seasons, Wentz has been above average when passing from 0/1 step drops and 5-step drops, but struggled tremendously from 3-step drops. And that story has been the same for the last two years.
In 2018, Wentz ranked first in the NFL in success rate and positive play rate (rate of plays where EPA was positive) from both 0/1 and 5-step drops combined and had the fourth-best rating.
But on 3-step drops, his positive play ranking dropped from first to 22nd (from 56.3% to 48.4%), his success rate ranking dropped from first to 23rd (from 59% to 51%), and his EPA dropped from 0.12 EPA/att to -0.03 EPA/att.
In 2019 the story was similar, though slightly worse due to the caliber of receiving targets. From 0/1 and 5-step drops, he ranked third in success rate (56%), eighth in positive play rate (51.3%), and 11th in EPA/att (0.08 EPA/att).
But from 3-step drops, his success rate ranking dropped from third to 32nd (from 56% to 46%), his positive play ranking dropped from eighth to 29th (from 51.3% to 43.2%), and his EPA rank dropped from 11th to 37th (from 0.08 EPA/att to -0.12 EPA/att).
These are large enough sample sizes of passes happening in consecutive seasons with not small but massive drops in productivity. The Eagles should be able to dig in deeper to determine how to raise Wentz’s efficiency on 3-step drops or reduce their usage.
I forecasted the 2019 Eagles would face the NFL’s third-easiest schedule last summer and was close, as they actually faced the seventh-easiest. But I project the Eagles will face the 19th easiest schedule in 2020, making them deal with the fifth-toughest year-over-year schedule increase. The Eagles’ toughest stretch by far comes from three consecutive games against the 49ers, Steelers, and Ravens. But it’s not any ordinary stretch. They must travel to play the 49ers for a Sunday night game. Such night games on the West coast are notoriously difficult for East coast teams. Then, they must travel to face Pittsburgh on a shorter-than-average week and then take on the Ravens. Later in the year, the Eagles must travel to Green Bay on a short week after a Monday night game. These opponents are difficult enough, but the situations make things even more challenging. The biggest change for the Eagles compared to 2019 will be the offenses faced. In 2019, Philadelphia faced the NFL’s eighth-easiest schedule of offenses. I project they will face the sixth-toughest in 2020. In 2019, when playing offenses that finished the season ranked top-20, they went 2-6 (and went 7-1 in their other eight games). In 2020, the Eagles face 10 offenses that ranked in the top-20 last year.
