---
title: Jacksonville Jaguars
author: ''
date: '2020-09-04'
slug: jacksonville-jaguars
categories: []
tags: []
---


Help a young quarterback. Find out what he does well, quickly, and emphasize it. Keep him from obvious passing situations. Keep the defense guessing with your playcalls. Keep him confident by keeping him upright. And let him pass on early downs to build up his confidence.
The formula to helping a young quarterback goes beyond that handful of strategies, but they get you pretty far down the road.
John DeFilippo didn’t expect to be working with a young quarterback. He was hired to be the Jaguars’ offensive coordinator in January 2019. Blake Bortles was still the Jaguars’ starting quarterback, but clearly head coach Doug Marrone discussed ideas for what the Jaguars would do at the position in 2019. In free agency, the Jaguars went hard after Nick Foles. Foles was the Eagles’ backup quarterback and took the Eagles into the playoffs twice. He did so once and won a Super Bowl with DeFilippo acting as quarterbacks coach.
The Jaguars overpaid for Foles in free agency, as teams tend to do when signing players in free agency. They released Bortles and DeFilippo was back to working with Foles. That was the plan for 2019. The team drafted Gardner Minshew in the sixth round as an afterthought.
The depth chart as of May 1 was QB1: Foles, QB2: Cody Kessler, QB3: Tanner Lee, QB4: Minshew.
But the Jaguars released Kessler on May 9. And everyone bumped up one spot. And then, in the midst of the preseason, the Jaguars released Lee on August 17.

And boom, just like that, behind Foles was Gardner Minshew,
QB2, a rookie sixth-rounder.
Trailing 10-0 to the eventual Super Bowl champion Kansas City Chiefs, Nick Foles
dropped back on 3rd and 8 and bombed a 35-yard touchdown to D.J. Chark. But he was blown up on the play. He ended up breaking his left clavicle and needed surgery. He was put on IR with a designated to return tag. His season wasn’t over, but he would be out for a couple of months.
Suddenly, before it really got started, the DeFilippo/Foles reunion was over. And DeFilippo was left with a sixth-round rookie, who wasn’t prepared at all.
Learning a new offense with new teammates isn’t easy. With both DeFilippo and Foles in Year 1 with a new team and teammates, you can imagine Foles and the first-team offense did a lot of work in the preseason. This was not a Kyler Murray situation, where the plan was to get the young pup ready for Week 1 and give him meaningful reps all preseason. Minshew was an afterthought in the draft and in the preseason. And here he was, in Week 1, dropping back to pass 25 times against the NFL’s best QB and eventual Super Bowl MVP Patrick Mahomes.
That Week 1 game saw Minshew impressively go 22/25 for 275 yards (11.0 YPA), but the team obviously lost 40-26.
It’s hard not to feel for DeFilippo. But injuries happen. And it was time to get to work figuring out how to maximize the offense to do as best possible with Minshew as QB1.
There were a couple of pitfalls DeFilippo didn’t fall into, which was good. But there were also things that were beyond head-scratching, to be kind. For the purpose of the analysis of the DeFilippo-Minshew marriage, I’m removing Week 1 and Weeks 11-12, when Foles returned before exiting again for good in Week 13.
One of the first pitfalls many playcallers fall into with a young quarterback is a desire to get conservative. They believe a young quarterback’s best friend is the run game, his enemy is too many dropbacks, and the run game should carry the burden with the quarterback passing when he needs to.
But the reality is, a young QB’s best friend is passing on non-obvious passing situations. His enemy is passing on obvious passing situations. The run game should support and complement the quarterback, not attempt to carry him unnaturally.
To his credit, DeFilippo didn’t fall into that first pitfall. I wrote in last year’s preview about DeFilippo’s time with the Eagles before going to Minnesota in 2018. I forecast that, with his wings spread after Mike Zimmer’s conservative approach caged him, DeFilippo would return to a more pass-oriented attack (a la the Eagles style) in Jacksonville. Had Nick Foles been QB1 all season, perhaps the Jaguars would have gone even more pass-heavy. But with Minshew at the helm, they were fairly balanced.

Still, it was much more pass-heavy than the 2018 Jaguars. In fact, even with a rookie QB, the Jaguars passed the ball 6% more in one-score situations, the fourth-highest increase in the league.
In the first half of games, on first down the Jaguars were 49% pass. That was right in line with the NFL average. They were the third-most run-heavy team in this situation in 2018 (42% pass). Even while the Jaguars ran less often, the problem was when they did run it was an absolute disaster.
The Jaguars averaged just 2.9 YPC and a 27% success rate. That ranked 31st and 32nd in the NFL.
Of 41 running backs with 30+ first half, first down carries last year, Leonard Fournette ranked dead last. His 2.7 YPC was dead last. His successful play rate of
25% ranked dead last.

On 75 attempts, he had just four broken tackles. These 75 runs recorded -16.4 EPA.
In other words, starting out the game (first half), when the Jaguars stuck the ball into the belly of Fournette, they stuck the knife in their own belly and slowly but steadily killed their chances of winning games.
Meanwhile, on first down passes in the first half, Minshew was great. He had 73 attempts, nearly identical to the number of runs for Fournette. But Minshew averaged 7.8 YPA and delivered a 90% accuracy rate. He threw just one interception. He recorded a 105 rating, a 63% success rate, and 9.5 EPA. Of 31 quarterbacks to throw at least 40 attempts, Minshew posted the sixth-best success rate.
While the Jaguars were not overly run heavy on these downs, they were so terrible when rushing (41st of 41) and so great when passing (sixth of 31) that they needed to go more pass-heavy.
Team More Rest 4 3 Net Rest Edge 1 We saw the Jaguars pass the ball at an above-average rate on first downs in the first half with Minshew at the helm in just four games out of 12:
Week 3 vs the Titans (67% pass) Week 4 vs the Broncos (57% pass) Week 9 vs the Texans (78% pass) Week 17 vs the Colts (79% pass)
The Jaguars’ record in those four games where DeFilippo allowed Minshew to pass more on first half first downs?
3-1
In every other start, the team skewed even more run-heavy than average. And as we just learned, with each first down handoff to Fournette, the Jaguars were less and less likely to win.
This strong run rate with disastrous results was a big reason why the Jaguars held a halftime lead in just two games all season long. No other team held fewer halftime leads. The next closest teams were the Redskins and Giants, both at four games.
Over the last 30 years, only five teams held a halftime lead in fewer than two games. It hasn’t happened since 2012. And only 12 other teams in those 30 years held a halftime lead in just two games. The last time prior to the 2019 Jaguars was the 0-16 Browns of 2017.
The frustrating part was this was entirely on playcalling. The score was not out of whack. It was the opening drive. It was the late first quarter. It was 20 minutes into the game. It was just the first half. And on first downs, where the defense didn’t know if you would run or pass, which means a great opportunity to pass, the Jaguars chose balance over efficiency. And it directly translated into more losses.
But even more frustrating than the first half run rate (because to be fair, it was league average), was the lack of tools that were made available to Minshew. And those tools are play-action and pre-snap motion.
The 2019 Jaguars used play-action on just 25% of their early down pass attempts in the first three quarters. That ranked 30th in the NFL, or third-least often.

And I simply don’t understand the justification for such a low rate. Let’s pretend that Minshew was just average in play-action.
Let’s pretend he averaged 8.5 YPA with play-action as opposed to 6.7 without.
Let’s pretend he averaged a 55% success rate with play-action as opposed to 51% without. Let’s pretend he averaged a 103 passer rating with play action as opposed to 90 without.
You have a running back like Fournette in the backfield. He’s clearly terrible when running behind this line, especially on these early downs to start the game. You know defenses will *think* you will want to run the ball because you have a No. 4 overall pick at running back and a rookie sixth-round quarterback, so they might try to play the run more. And you know your quarterback is significantly better when using play-action (using the NFL average stats above).
How could you possibly justify using play-action the third-least often in the NFL?
But wait, it gets worse. And that’s because Minshew didn’t just improve like the NFL average when using play-action. He was OFF THE CHARTS great.
How about these splits (early downs, quarters 1-3 as defined above):
With play-action: 11.2 YPA, 68% success, 147 rating, 61% positive play, 0.48 EPA/att, 9.3% TD rate W/O play action: 5.3 YPA, 44% success, 76 rating, 45% positive play, 0.04 EPA/att, 1.9% TD rate
Among 32 quarterbacks with at least 40 play-action attempts, Minshew ranked first in EPA/att, first in positive play rate, first in success rate, first in rating, first in accuracy, first in TD/INT ratio, and fifth in YPA.
He wasn’t just average with play-action. He was the best in the NFL. And his splits were the largest in the NFL. He was first with play-action and gained the biggest benefit by using play-action. You can look at the “Offensive Efficiency & Tendency Research” section of this chapter, line 22, and see how little they used it but lines 23 through 25 show how great they were with it.
And yet the Jaguars used play-action at the 30th-highest rate of 32 teams. It made zero sense. And this gets back to the second sentence in this chapter: “Find out what your
young QB does well, quickly, and emphasize it.” The Jaguars failed hereby not using more play-action.

Using both free agent Nick Foles and sixth-round draft pick Gardner Minshew under center last season, Jacksonville ranked 27th in success rate through the air (42%) and 23rd in EPA via their passing offense. Minshew threw 21 touchdown passes to just six interceptions on 556 dropbacks, but completed 60.6% of his passes while his expected completion percentage was 65.8% per NFL Next Gen Stats. That -5.2% mark under expected completion rate bested only David Blough for all qualifying passers a year ago. His 7.9-yard average depth of target ranked 28th while his 7.0 yards per pass attempt ranked 23rd for all passers with four or more starts on the season. The Jaguars shipped Foles off this spring to the Bears, giving Minshew the opportunity to be the full-time quarterback in Jacksonville for the 2020 season.

Jacksonville struggled to use their tight ends (30th in yards per target) and their running backs (26th) in the passing game last season. Leonard Fournette had 100 targets in the passing game last season, but ranked 50th in successful play rate in the passing game among backs. New addition Chris Thompson checked in at 54th on the same list in 2019. The Jaguars ranked 26th in success rate targeting their wide receivers, but that wideout group did rank 16th in the league in yards per target (8.1 yards). The team received a big breakout from D.J. Chark (73-1,008-8) in his second season. Chark is the lead option in the passing game moving forward while Laviska Shenault, Tyler Eifert, and Thompson are new contributors here in the passing game.

The Jaguars ranked 30th in success rate rushing (41%) ahead of just the Jets and Dolphins while ranking 26th in Expected Points Added on the ground. Despite Leonard Fournette tallying 1,152 yards on the ground, he ranked 42nd out of 47 running backs in success rate (42%) to have 100 or more carries on the season. The Jaguars also just could not find the end zone on the ground, registering a league-low three rushing scores in 2019, which was the fewest rushing touchdowns in a season for a team since 2005. With no major additions to the backfield to significantly threaten Fournette’s workload, the team projects to lean on the power back once again in the final season of his contract.

Is Gardner Minshew an underrated fantasy option?
Minshew had his faults as a passer and “real” quarterback, but was a reliable fantasy option. Minshew made 12 starts last season and finished in the top half of weekly scoring at his position in nine of those 12 weeks. His 16.8 fantasy points per game in those starts were good for the QB16 on the season, ahead of options such as Kirk Cousins, Tom Brady, Jared Goff, and fellow rookie Daniel Jones. What helped Minshew sustain a high floor was that he led all NFL quarterbacks in scramble rushing attempts (50) and was 13th in rushing points per game (2.6). Still a streaming and bench option in 1QB formats, Minshew is a solid late-round value pick in 2QB formats with an undervalued floor.
What do we do with Leonard Fournette in 2020?
One thing in short supply in fantasy football are running backs with volume. Even with inefficiency, we want players who get the ball a lot, and that is what we have with Fournette. He is coming off a career-high 341 touches while handling 85.8% of the Jacksonville running back carries and 84.8% of the backfield touches. Despite sitting out Week 17, those rates of usage trailed only Christian McCaffrey at the position. The depth chart behind him right now is filled with inexperienced, low-investment options and satellite back Chris Thompson, who comes with his own set of baggage in terms of staying on the field.
Fournette is also due to have a spike in touchdown output, even playing for the lowly Jaguar offense. He scored just three times on those 341 touches. It was the fifth-most touches in an NFL season with three or fewer touchdowns scored. There have been five times in league history where a back has scored three or fewer times on 300-plus touches and received another 300-plus touches the following season. In those years, the touchdown spikes for those backs resulted in scoring seasons of 14, 15, 11, 15, and seven touchdowns. Jacksonville also had a 24-to-3 passing to rushing TD rate (88.9%), the second-highest split over the past decade behind the 2017 Seahawks, who went from four touchdowns on the ground up to 15 the following season.
The question still remains in how we trust the Jaguars and can Fournette get to 300 touches again in 2020? On one hand, the Jaguars seemingly are not too enthralled with Fournette on the field or behind closed doors. They tried to trade him this offseason and declined to pick up his fifth-year option. But on the other hand, the team also failed to aggressively add any real competition or investment into the depth chart from a rushing perspective behind Fournette.
The shakiest thing for Fournette is that his 2019 receiving role should be compromised. Fournette set a career-high with 76 catches and 100 targets, but did so with only 6.9 yards per catch and had 19 total air yards all season on those targets. The Jaguars added Thompson, who has familiarity with Jay Gruden, to take away receiving snaps but has played a full season just once in seven years and has missed five or more games in each of the past three seasons.
Fournette has the projected workload and scoring regression to the mean as pros to him being a potential value option with a high floor, but also comes with added fragility due to his standing with the organization and potential loss of a career-high in receiving output.

Jacksonville had one of the most feared defenses in the league just a few years ago but that time has long past. The stars of that team are all gone and the Jaguars are in the midst of a rebuild at every level of defense.
The loss of Calais Campbell will be felt across the entire defensive line, but 2018 first-round pick Taven Bryan had an impressive sophomore campaign as a pass rusher with a 9.72% pressure rate that ranked fourth behind Aaron Donald, Chris Jones, and Javon Hargrave among defensive tackles with at least 100 pass rushes. There’s little of note behind Bryan, though veterans such as Abry Jones and Rodney Gunter should be fine if Bryan can continue to develop. Jacksonville also used a third-round pick on Davon Hamilton, who mostly played a nose tackle role at Ohio State.
The Jaguars pass rush hinges on whether Yannick Ngakoue will be on the team for the 2020 season and beyond. Ngakoue was offered the franchise tag but has made his desire to move on from Jacksonville well known. Josh Allen had an impressive rookie season and there is still room to grow. The Jaguars drafted LSU EDGE K’Lavon Chaisson with their second first-round pick to add to the rotation and have a possible starter when/if the team and Ngokue part ways.
With Myles Jack and free agent signing Joe Schobert, the Jaguars rival the Cowboys with the most investment at off-ball linebacker (quality may vary). Jack signed a huge extension a year ago but took a huge step back in play during the 2019 season. He’s cuttable after 2020 with nearly $5 million in cap savings, but with so many other needs on the defense, it’s more likely the Jaguars will allow that to play out before potentially addressing a permanent fall off early.
At this time last season, the starting cornerback duo was Jalen Ramsey and A.J. Bouye. This is not that. D.J. Hayden was a standout last season in the slot (10th in Adjusted Yards allowed per coverage snap among corners with 100+ snaps) but he might have to take on more responsibility in 2020. The Jaguars selected C.J. Henderson of Florida ninth overall. Henderson struggled in coverage during his final college season but is very, very fast.
Rashaan Melvin was a bottom-tier corner with the Lions last season but will battle as the other outside starter, as will Tre Herndon, who was slightly below average in his first season as a starter.
At safety, Jarrod Wilson played admirably for a fourth-year undrafted free agent who was pushed into his first starting role in 2019. Ronnie Harrison also showed some promise in his third season. Still, the Jaguars were among the worst teams defending the deep ball and there’s little to no depth behind the penciled-in starters.

Next is pre-snap motion. Through three quarters, the NFL average is using pre-snap motion ahead of 39% of passes, 49% of rushes, and 43% of all plays.
The Jaguars ranked 32nd in pre-snap usage rate, at 24%. And specifically for passes, as we talk about helping a young quarterback they ranked 32nd with just 18% usage. That’s less than half the rate of the league average (39%).
Look at the five teams that used the most pre-snap motion ahead of passes last year & their usage rate over the first three quarters of the game:
Chiefs: Super Bowl champions & AFC No. 2 seed (53%) 49ers: Super Bowl & NFC No. 1 seed (66%)
Titans: AFC Championship & AFC No. 6 seed (63% ) Ravens: Best regular season record & AFC No. 1 seed (57%) Patriots: AFC No. 3 seed (65%)
Pre-snap motion helps quarterbacks discern if the defense is playing man or zone coverage. It helps determine leverage. It allows your quarterback to see who is moving defensively and can allow him to better predict what the look will be postsnap. There is inherent value to pre-snap motion.
And best of all, it is free. It costs nothing. It takes no talent. Put your player in motion and peak behind the curtain free of charge.
And yet the NFL average is only 39% in quarters one through three. Where was Jacksonville?
32nd.
They used it only 14.5% of the time (17.8% in quarters 1-3). No other teams were remotely close to that low level of usage. They were far and away last in the league.
Did it help Minshew? Not nearly as much as play-action, but it didn’t hurt. His success rate increased by 1%, his TD:INT ratio improved, his passer rating improved by seven points but his YPA declined by 0.4 YPA. That was largely due to aDOT. When using pre-snap motion ahead of a pass, Minshew’s aDOT was only 4.6 yards downfield. When not using pre-snap motion, his aDOT was 7.7 yards downfield. Clearly, most if not all of that 0.4 YPA decline was related to the play calls themselves, rather than his own performance.
But more than anything, his sack rate improved tremendously with pre-snap motion. When using pre-snap motion: two sacks on 91 dropbacks (2.2%). Without, the Jags took 39 sacks on 538 dropbacks (7.2%).
If the 2020 Jaguars want to do something other than tank, they need new offensive coordinator Jay Gruden to study what worked for Minshew and do more of it.
The Jaguars face the seventh-toughest increase in schedule strength in 2020 as compared to 2019, but it won’t seem that difficult to start the season. In fact, the Jaguars play the NFL’s second-easiest schedule and easiest schedule in their first eight games. They play just two teams forecast to produce a winning record (Colts and Titans). They are fortunate to host a Thursday night game (against the Dolphins) and they have a Week 7 bye to prepare for a trip to visit the Chargers in Los Angeles.
However, from Week 10 onward, the Jaguars play the NFL’s second-toughest schedule. Their final eight games feature zero teams projected to post a losing record. Seven of their final eight opponents are forecast to win over eight games.
Much is often made about Florida teams hosting early-season games as a big advantage, due to the heat and humidity. But historically, the Jaguars win and cover just 49% of home games the first month of the season (23-24-2 ATS). A seemingly better edge are late-season games in Florida, as the Jaguars win and cover 56% of these games. Note that when playing at home since 2010, Florida teams (Jaguars, Dolphins, and Buccaneers) win 35% and cover 32% of games the first month of the season but win 45% and cover 46% of games in the last month of the season.

