---
title: Browns
author: ''
date: '2020-09-04'
slug: browns
categories: []
tags: []
---
“If you know the enemy and know yourself, you need not fear the result of a hundred
battles. If you know yourself but not the enemy, for every victory gained you will also
suffer a defeat. If you know neither the enemy nor yourself, you will succumb in every battle. Sun Tzu knew the value of knowing yourself. The Browns didn’t know themselves last b year, particularly on offense. And that lack of knowledge, coupled with infighting and b
ultimately insurrection amongst the coaching ranks propelled the Browns from capitalizing on their 7-9 2018 campaign.


Under Hue Jackson in 2018, the Browns were very much an 11 personnel passing attack. .In quarters 1-3, they used 76% 11, 15% 12, and nothing else more than 5%.
But they were very inefficient. Those passes from 11 recorded 5.5 YPA, a 71 rating, an
11% sack rate, and a 39% success rate.

When Jackson was fired, Freddie Kitchens took over as offensive coordinator and .playcaller. Under Kitchens in quarters 1-3, the Browns used 11 personnel on only 64% of
pass attempts and increased heavier packages, including 15% from 12 and 8% from 13
as the next two most used groupings after 11.

Kitchens reduced 11 personnel passes by 16% (12 percentage points) and increased formational diversity. Whereas Jackson only used two groupings at least 7% of the time and three used at least 4%, Kitchens used four different groupings at least 7% of the time with five used at least 4%.
Increasing the blockers and diversity clearly helped.

When not always using typical 11 personnel, Baker Mayfield’s efficiency shot up in the newly used heavier sets. But his efficiency in 11 increased as well, thanks to the offense showing less of it and using it more tactically.
2019 Passing Performance
When Freddie Kitchens became head coach following his stint as offensive coordinator, I anticipated we would see more of the offense he used at the backend of 2018. More of what he wanted to do. Less of the 11 personnel based offense that Jackson used and in which Mayfield struggled tremendously.
Absolutely I anticipated a lot of new wide receiver Odell Beckham Jr. on the field along with Jarvis Landry, but the team added tight ends Demetrius Harris and Ricky Seals-Jones in the offseason to partner with David Njoku. They also added Kareem Hunt to assist Nick Chubb with running back duties. There was plenty of opportunity for personnel diversity.
But there was a key hiring that may have changed the course of that strategy. The Browns hired Todd Monken to function as offensive coordinator. Monken had a background in Air Raid and Air Coryell systems with previous playcalling experience. Whereas Kitchens spent most of his career coaching running backs and tight ends, he had never called plays before doing so on an interim basis for the 2018 Browns.
Piecing reports from January 2020 and the aftermath of the Browns 6-10 season with the pre-season and in-season offensive deployment sheds some light on the controversial and puzzling offense.
Kitchens was to call plays for the 2019 Browns and Monken’s role was “to help Kitchens” and said his lack of calling plays was “a non-issue.”
But as I do in the pre-season, I examined the team’s personnel grouping usage, and I found something extremely puzzling. Neither Beckham nor Landry played at all in the preseason games, so they were down their top-2 WRs. They had all three tight ends healthy, plus a cadre of running backs.
And yet the Browns used 85% 11 personnel in the preseason, compared to 56% in 2018. And they used only 12% 12 personnel, compared to 21% in 2018. They didn’t use any other grouping over 2% of the time.
We knew how formationally diverse the Browns were when Kitchens took over in 2018. And we knew how their top-2 receivers were both absent these games. The combination of both factors made it extremely puzzling they were pivoting so hard to 11 personnel in the preseason.
Studying the numbers, I said last August in my annual preseason personnel groupings report: “this offense might be operating from spread a lot more than in 2018” based on what I witnessed in the preseason.

I believed the playcalling may come from Kitchens, but the system and general philosophy could have been influenced by Monken’s Air Raid background. If so, we naturally would see more receivers on the field, less 12 and 21, and a change from 2018’s Kitchens-styled play calling. The preseason was one thing and I was extremely interested to see the regular season strategy.
Unfortunately for the Browns, it wasn’t good.
In Week 1 through 9, 84% of their passes came from 11 personnel. Almost identical to the 85% they utilized in the preseason.
In the first three quarters, they used 11 on 84% of pass plays as compared to 64% with Kitchens in 2018.

The skeptic might suggest that the usage of 11 was because David Njoku went down with an injury in Week 2 and didn’t play again until Week 14. However, the team still had both free agent tight ends they signed and importantly, things hadn’t changed from 2018:
Baker Mayfield was substantially more efficient passing in anything besides 11 personnel.
Look at the production splits in Week 1-9:
From 11: 6.8 YPA, 39% success, 69 rating, 3:6 TD:INT Non-11: 8.6 YPA, 55% success, 115 rating, 3:0 TD:INT
Yet the Browns continued to use 84% 11 personnel and stumbled to a 2-6 record over the first half of the season.
Even if one wanted to argue the Browns were deeper at receiver after Njoku’s injury, I would tell them three things:
First, you always want to use your more productive sets.

Even without Njoku, 12 and every other non-11 grouping was much more efficient, so scale back on 11.
Second, the Browns also dealt with injuries to wide receivers Antonio Callaway and Rashard Higgins. The Browns’ No. 3 and 4 receivers both played in less than half of the team’s 2019 games. Just in Weeks 1 through 9, there were a combined nine games missed between the two, and they both missed Weeks 2, 3, and 4. These absences certainly don’t justify more 11 personnel.
And lastly, but most importantly, we can just look at what the Browns did to start the season when all tight ends were healthy:
They started Week 1 using 11 personnel and of their 42 pass attempts, 40 (95%) came from 11 personnel.
Week 2, with a still healthy Njoku, they started the game with 10 personnel (4 WRs and zero TEs) and used 11 personnel on 34 of 38 attempts (89%) despite thrashing the Jets 23-3. Most teams would shift to more runs and passes from heavy sets with a larger lead, but not the Browns.
Those two games coupled with the preseason told me all I needed to know about the 2019 Browns offense. Kitchens may be calling the plays, but make no mistake it was way different from 2018 and was now heavily influenced by Monken.
I couldn’t believe what I was watching.
In the first three quarters of games through Week 9, as the Browns struggled to a 2-6 record, they used 84% 11 personnel despite all of the data showing how bad they were in 11 and solid they were in anything else.
It was tangible on Mayfield too. It wasn’t just his passing splits which I shared earlier that he was statistically much better than average when using non-11 to pass, but one of the worst quarterbacks in the NFL when using 11. It was the pressure and sack rates when he was in 11 vs other groupings.
With added bodies to either directly assist in protection or give a pre-snap look like there might be extra protection, Mayfield was sacked just once. But in 11 personnel, he was sacked 12 times and pressured much more often. His sack rate was over double in 11 personnel and the pressure rate was similar. He wasn’t getting the protection and his productivity reflected a quarterback without confidence.

I also couldn’t believe what I was hearing.
Multiple pundits around the nation, as well as many Cleveland Browns fans, raised the call that the team “needs more Monken!” Having done the research, however, I thought “perhaps too much Monken is the problem,” and I was shocked people couldn’t recognize what I was watching.
We would hear after the season about power struggles between Monken and Kitchens during the season. Monken apparently walked up to opposing coaches before games and told them the Browns were “a total mess”.
The weekend of their Week 9 game in Denver, I used my resources to investigate and asked about the level of Monken’s influence. The response was as I predicted: too much. But with that came an assurance that it was going to change, and soon. Boy, did it ever.
Take a guess at how much 11 personnel the Browns used the very next week, Week 10, in the first three quarters? Just 41 percent! Down from 84% on the season up until that point. And over the course of the rest of the season, not one game saw more than 56% usage of 11 personnel to pass in the game’s first three quarters. Starting with that Week 10 game, the Browns won four of five games and sat 6-7 on the season.
But it still wasn’t all beautiful. Heading into Arizona in Week 15, the Browns used 50% 11 personnel in the first three quarters, their highest rate in over a month. Mayfield was predictably terrible in 11 (3.6 YPA, 30% success, 0:1 TD:INT, 9% sack rate) and the Cardinals blew out the Browns.
Kitchens was rightfully relieved of duties. The Browns’ playcalling struggled all season and it truly was a waste of what was a talented roster.
As disappointed as I was in the 2019 Browns, I’m as excited for 2020 and it’s almost entirely because of coaching. Kevin Stefanski is now the head coach and playcaller. The 2019 Vikings used 3+ WRs on only 22.9% of snaps, by FAR the least often in the NFL. The NFL average was almost triple that rate (64.6%). Instead, they used a ton of 2-TE & 2-RB sets.
And wow, did the Browns load up on personnel to execute such a plan. They added fullback Andy Janovich, tight end Austin Hooper, and right tackle Jack
Conklin in free agency. They drafted left tackle Jedrick Wills and tight end Harrison Bryant.

Baker Mayfield took a step back last season with his completion rate (59.4%), touchdown rate (4.1%), and yards per pass attempt (7.2) all declining off his rookie rates while his interception rate went from 2.9% up to 3.9% in 2019. Facing the hardest passing schedule in the league in 2019, Cleveland ranked 23rd in success rate per pass play (42%) and ranked 28th in the league in missed yards per pass attempt (3.7 yards). The one bright spot for Mayfield is that he was excellent using play-action. 37.3% of Mayfield’s yardage came off play-action, the fifth-highest rate in the league, and was third in the league in touchdown passes (11) using play-action, which accounted for half of his touchdown passes. Mayfield will now work with his third offensive coordinator in three seasons in Kevin Stefanski. Stefanski’s approach is built around selling nearly every play as a run play, opening the door to build off the best aspect of Mayfield’s 2019 season.

The Browns ranked below average in league success rates per target to every position in 2019. They were 25th in success rate targeting both their wide receivers (48%) and tight ends (46%) and 17th targeting the running back position (44%). With big money spent on wide receivers Odell Beckham and Jarvis Landry, Cleveland went out and opened their wallets for Austin Hooper this offseason. The Cleveland passing game will be asked to take a major step forward in efficiency over volume in Stefanksi’s offensive scheme. No team used 11 personnel less than the Vikings in 2019 (25% compared to a 60% league rate) while Minnesota was second in use of 12 personnel (34% compared to 20% league average).

The Browns ran for 1,901 yards in 2019 (12th in the league) and averaged 5.0 yards per carry, which ranked fifth. Despite their per-carry efficiency anchored by long runs, the team ranked 14th in EPA via their rushing offense and 21st in success rate rushing (46%). Running back Nick Chubb finished second in the league in rushing yardage (1,494 yards) and was 10th among all running backs with 100 or more carries in explosive run rate (13%). Adding Kareem Hunt to the fold for the final eight weeks, the Cleveland backfield combined for 158.5 yards from scrimmage over that span. With Stefanski’s Kubiak-ian offensive playcalling and design influence, the combo of Chubb and Hunt will be a large part of the offense in 2020.

The Browns May Play Faster Than You Think
While we know new head coach Kevin Stefanski wants to base his offense on the appearance of the run game, the actual pace at which the Vikings played in a neutral game script was much faster than you would believe. Minnesota led for 47% of their offensive snaps on the season, which was seventh in the league. As a byproduct of Minnesota leading often, they ranked 16th in the NFL in overall pace of play, running a play every 27.7 seconds of possession. But they ranked 21st in the league in pace of play playing ahead on the scoreboard at any point (29.2 seconds per play) and 27th in pace ahead in the second half of games (31.6 seconds). Adjusting for game script, Minnesota had much more tempo. They ranked ninth in the NFL in pace in neutral game script outside of the fourth quarter of games (28.2 seconds) and sixth in offensive pace trailing at any point in the game (24.6 seconds per play). In the first half of games period, they were eighth in pace played (26.6 seconds).
For comparison, the 2019 Browns were 20th in first half pace of play (28.4 seconds), 27th in pace in neutral game script outside of the fourth quarter (30.4 seconds), and 26th in pace while trailing (27.4) at any point. Unless Cleveland can match the 2019 Vikings in terms of overall positive game script, we can project the Browns to run more offensive plays in 2020 than they did in 2019 (which was actually only three more plays than the 2019 Vikings), which would offer more upside that is being led on by the concerns that Stefanski is out to solely ground and pound opponents.
Can Odell Beckham Rebound in 2020?
Beckham’s expectations are so high that he has made back-to-back 1,000-yard seasons end up as disappointments. Through a cocktail of changing teams, not playing up to par, facing the league’s hardest passing schedule, and playing through a sports hernia, torn abductor, and torn rectus, Beckham closed 2019 at WR25 overall and WR34 in points per game (12.6) while having career-lows in targets per game (8.3) and yards per target (7.8). The Browns faced 10 opponents in the top half of the league in point differential allowed versus opposing wide receiver average and had just three games against defenses in the bottom 10.
But even in a down year through all that worked against him, he still ranked 12th overall among all wide receivers in targets (133), fourth in end zone targets (13), 12th in expected fantasy points, and eighth in weighted opportunity rating at the position. Beckham is unlikely to receive double-digit targets per game in this Cleveland offense such as he did early in his career with the Giants, but the injury and letdown discount on Beckham from 2019 has room to be advantageous, especially if he ends up as your WR2 option.

The Cleveland defense never really clicked with Steve Wilks but Kevin Stefanski brought in Joe Woods to be the defensive coordinator after Woods helped the San Francisco secondary last season. He also had a successful stint as the Denver defensive coordinator after Wade Phillips left for the Rams. Sheldon Richardson was the prize of last offseason but didn’t put up the pass rush production he had with the Vikings in 2018 or near his peak with the Jets. Richardson was 24th among defensive tackles in pressure rate with at least 100 pass rush snaps last season and his quarterback hits dropped from 16 to six. But even with that, he was a plus run defender and even just a good pass rush makes him an above-average interior defender. The same can be said for Larry Ogunjobi and free agent signing Andrew Billings. Both have the ability to play the run well with the upside of pass rush disruption. Billings was a starter for the Bengals last season and will likely push Ogunjobi for that spot with the Browns. That’s a solid three-man rotation and Jordan Elliott was added in the third round.
Last year Myles Garrett was one of the league’s best edge rushers, fourth in Pass Rush Win Rate. Olivier Vernon remains a player who consistently puts up a high pressure rate without matching sack production and time missed due to injury. Adrian Clayborn gives the Browns a productive backup they didn’t really have on the roster last season. Despite Garrett’s presence (and especially without him during his suspension) the Browns ranked just 18th as a team in Pass Rush Win Rate per ESPN and 12th in pressure rate per SIS.
Joe Schobert had a down year last season, but even with that his loss will be felt in this group. Mack Wilson stepped into a role as a fifth-round rookie but was often overmatched. B.J. Goodson struggled in the linebacker no-mans-land of Green Bay, but was an underrated player previously with the Giants. Sione Takitaki might have the most upside of this group but that’s an incredibly low bar and he was on the field for just 10.4% of Cleveland’s defensive snaps as a three-round rookie. Third-round pick Jacob Phillips will also factor into the rotation.
With Denzel Ward and Greedy Williams, the Browns have an impressive, young duo at outside corner. Ward was about average by Adjusted Yards allowed per coverage snap last season while Williams struggled a bit as a rookie. Still, there’s plenty of potential for improvement in Year 2, something typically seen at the position. Cleveland got an impressive add in free agency with Kevin Johnson, who worked well both outside and in the slot for the Bills last season (22nd of 145 corners with 100+ coverage snaps in AYa/CS.
The Browns will have a completely new safety tandem this season. Karl Joseph has the ability to play a high-level single-high safety but has not yet managed to stay on the field for a full season. Andrew Sendejo mostly epitomizes the veteran journeyman defensive back. First-round pick Grant Delpit will make an immediate impact and can push in as a starter. The Browns might also go with more three-safety looks on the back end.

They can roll 2-TE sets featuring Beckham and Landry at receiver, tight ends Njoku and Hooper, and either Chubb or Hunt in the backfield.
They can roll 2-RB sets with Janovich leading the way for Chubb or Hunt or have Chubb and Hunt on the field together, which worked well in limited plays for the Browns in 2019.
The combinations are nasty. The unpredictability is nasty. And most important, it seems like this is what makes Mayfield comfortable. Yes, he played with Lincoln Riley and the Air Raid in Oklahoma, primarily against subpar Big 12 defenses. But through two full NFL seasons, it’s clear he’s been at his best with multi-back or TE sets. And that’s exactly what Stefanski is bringing to town.
No team sees their projected schedule improve from 2019 to 2020 more than the Browns. Last year they played the ninth-toughest schedule and I forecast them to play the third-easiest schedule in 2020. It’s not a perfect schedule, but there are several advantages.
They have extra prep for both games against the Ravens, being that one is Week 1 and the other is a home game on Monday night. They host their Thursday night game. And they have a bye right in the middle of the season (Week 9).
But even bigger than these spots is the schedule for Baker Mayfield. In 2019, they played the third-toughest schedule of pass defenses. They’re projected to play the easiest schedule of pass defenses in 2020. The Browns played 10 games against top-15 pass defenses in 2019 and went 3-7 in those games. They play only four top-15 pass defenses in 2020.
They move from the toughest schedule of total defenses in 2019 to the ninth-easiest in 2020. With a new offense, it will certainly benefit the Browns to play Week 2 and Week 3 at home against the lowly Bengals and Redskins, so they can iron out any early issues. Between Weeks 5 and 11, nearly two months, the farthest the Browns have to travel is to face cross-state rival Cincinnati.