---
title: Bengals
author: ''
date: '2020-09-04'
slug: bengals
categories: []
tags: []
---



Joe Burrow brings hope to the Bengals. .
  
But the Bengals will need to do more.


Last season, remarkably, the Bengals played in zero games before Week 17 where they snapped the ball over seven times from all personnel groupings combined other than 11
and 12.
You could argue this was due to a lack of talent, but I would argue that given a lack of
talent (particularly at the wide receiver position), that using the highest rate of 11 .personnel (3 WRs) on 76% of all offensive plays was not beneficial.
As the 2019 Bengals dropped to 0-7 on the season, this was their play count in all
personnel groupings combined, other than 11 and 12.

In the first three weeks of the season, no wide receiver saw a higher snap total than John Ross. But in Week 4, Ross was injured.
Yet in the four games from Weeks 4 through 7, the Bengals still used 11 personnel on 90%, 88%, 82%, and 94% of offensive snaps.
Why continue to use so much 11 personnel?
There was literally no adjustment to modify what they were doing. Week 3’s starting receivers were John Ross, Tyler Boyd, and Auden Tate.
When Ross went down in Week 4, 22-year old undrafted free agent rookie Damion Willis took his snaps. In Week 5, Willis took 40 snaps and Alex Erickson took 15. In Week 6, Zac Taylor demoted Willis and gave Erickson 49 of the 54 WR snaps at WR3. In Week 7, a game the team literally ran nothing but 11 (94% of snaps), Erickson took 68 offensive snaps.
In that final game, the Bengals used Erickson purely underneath. His average target depth was just 3.8 yards. He averaged 13.4 yards after the catch, breaking a 48-yarder. He had a good game, but the Bengals lost by double digits.
Why not use more 12 personnel, especially when Ross went down for half the season?
When the Bengals did use 12 personnel to pass on early downs, they were far better than using 11 personnel. Whether based on EPA, success rate, TD:INT, YPA, or passer rating, the Bengals were better in 2019 when passing out of 12 as compared to 11 personnel.
Yet the Bengals used the most 11 personnel in the NFL last year, and used it to pass on 82% of all pass plays, when down their No. 1 receiver all year and their then No. 2 receiver half the year.
For the first time since his rookie season, Tyler Eifert was healthy the entire year. He never played a 16-game season, until 2019. But despite that health, he went underutilized in Taylor’s offense. Instead, C.J. Uzomah started all 16 games.
Why not more from a finally healthy Eifert?
Of 63 tight ends with 50+ receptions from 2015 to 2018, Tyler Eifert ranked 10th in yards/target (8.5), ninth in touchdowns (19), and 10th in yds/game (46).

His prior problem wasn’t production or efficiency, it was health.

In 2019, in terms of receiving grades, Eifert graded out 28th of 69 tight ends, much higher than Uzomah.
Eifert absolutely could have been used more in the passing game with a receiving corps as shallow as Cincinnati’s but instead, the team opted to go with 3-WRs far too often. They could have paired Eifert and Uzomah more often along with Boyd and Tate.
But of 1,052 offensive plays last year, the Bengals used those four players on the field at the same time just 33 plays. Only 24 were pass plays, out of 664 passing plays on the season.
Why not put Eifert and Uzomah on the field together more often?

In Uzomah’s 644 offensive snaps, he was used to run block on 306 of them (47.5%). Of 79 qualifying tight ends, he ranked 69th in run blocking grade per PFF. Of 644 offensive snaps, Uzomah pass blocked on 74 (11%), and ranked 64th of 79. (Meanwhile, Tyler Eifert graded out fourth of 79 in pass blocking.)
Instead of putting Uzomah in positions to excel, he was asked to run or pass block on 380 of his 644 offensive snaps (59%) and he was terrible as a blocker in 2019.
Of the 264 times he ran pass routes, he was only targeted on 40 of them.
Of those 40 targets, only 29 graded as catchable and Uzomah caught 27 of them. But his average depth of target in 2019 was just 3.8 yards downfield.
Why not more targets and deeper targets for Uzomah?
In 2018, Uzomah’s depth of target was 7.0 yards downfield, he caught 39 of 45 catchable passes, and recorded a 54% success rate with three touchdowns. He was a productive receiver when targeted and was certainly capable of being targeted further downfield.
If Uzomah was on the field for 40 targets on 264 pass plays when he wasn’t blocking, he was targeted just 15% of these plays, and most of these targets were extremely short. More could have been designed for Uzomah, particularly more creative elements.
And then there was the skeleton key. The key that unlocked the entire offense if the defense knew about it. It was Taylor’s tell.
Tyler Eifert.
If Eiftert was on the field, there was an 81% chance it was going to be a pass play.
We’re not talking slight odds, we’re talking 81% odds.
And if Eifert was on the field without Uzomah, the Bengals passed the ball on 296 of 330 snaps! A massive 90% rate. It was ridiculously bad.
Why allow this to happen?
When Eifert last was healthy back in 2015, when he was on the field the team passed the ball 399 times out of 712 plays, or 56%.
Compare to some of the other Bengals last season:
If Uzomah was on the field, Taylor had a 50.4% pass rate. If Erickson was on the field, Taylor had a 64% pass rate. If Tate was on the field, Taylor had a 65% pass rate.
If Boyd was on the field, Taylor had a 66% pass rate.
Nothing was close to 80%, let alone 90% over the extremely large sample of 330 snaps.
Eifert is now a Jaguar, but year two of Zac Taylor absolutely must come with fixing the offense.

Taylor was hired by the Rams when Sean McVay was hired as the head coach in 2017. Taylor started as a receivers coach, then was promoted to quarterbacks coach in 2018. With just one year as a quarterbacks coach under McVay, Taylor was hired as the Bengals’ head coach for the 2019 season. He was the offensive coordinator once before in 2015, calling plays over the final five games of the season for the 6-10 Miami Dolphins. It is clear the Bengals didn’t invest in analytics or such a tell would be rooted out and ensured it wasn’t so obvious to opposing defenses. By using so much 11 personnel regardless of receiver health or talent elsewhere or a desire to confuse the defense via groupings, it is clear Taylor was taking a page out of his mentor McVay’s book of sticking with 11 because “that’s what we do.”
Over the course of the offseason, the Bengals flipped their spending on both sides of the ball. Their 2019 offense ranked fourth-most expensive and their defense ranked 10th-least expensive. In 2020, their offense ranks ninth-least expensive and their defense ranks 10th-most expensive. They signed a number of defensive free agents including DBs Trae Waynes, Vonn Bell, and Mackensie Alexander, in addition to defensive tackle D.J. Reader. Offensively, in addition to Eifert, the Bengals made the big move of moving on from Andy Dalton. The team drafted their quarterback of the future, Joe Burrow, with the first overall pick. Burrow inherits a team that has a lot of work to do, but has one positive in from the 2019 season: they went 0-8 in one-score games, and such teams almost always rebound. There have been 38 instances over the past 30 years that a team lost at least 8 games by one-score. Only seven of those teams won one or fewer games by one-score (thus teams with records between 0-9 and 1-8 in one-score games). Due to those teams’ inability to win one-score games, they recorded an average of only three wins apiece (Cincinnati won two games last year). But the following year, these teams averaged 6.1 wins per team, and their average record in one-score games improved from 0.9 wins and 8.4 losses to 3.3 wins and 5.6 losses.
While the Bengals rank as having the 11th toughest overall schedule, they may look much better when Joe Burrow drops back to pass. Not because he appears to be a great prospect, but because of how much easier their schedule of pass defenses appears to be. The Bengals played the toughest schedule of pass defenses in 2019, playing eight games against top-10 pass defenses. In 2020, that number drops to four. And they face the eighth-easiest schedule of pass defenses in totality.
Overall, they go from facing the fourth-toughest schedule of defenses to the 10th-easiest, including the eighth-easiest schedule of pass defenses. It’s the second-easiest jump for any team compared to 2019. And they start the season by facing three run defenses in their first four games that ranked 25th or worse last year. The other benefit for the Bengals is they face the Ravens in Week 17. By Week 17, it’s possible the Ravens have little to play for, so if there was a time to face the Ravens in 2020, playing them Week 17 is as good as it gets. But troublesome is the fact they play five games against opponents with more rest than they have. That means those opposing defenses have extra time to prepare for Burrow and Taylor’s offense. It is essential that the Bengals scrub all overwhelming tells like Eifert’s from their playbook. It is essential that they evolve Taylor’s preferred 11 personnel offense to optimize when possible to roster talent, injuries, and defensive weaknesses.
Some defenses have a great slot corner but have linebackers that struggle tremendously in coverage. It is a +EV move to force such teams to play more base by using more 12, 13, or 21 personnel. Second-year quarterbacks often take big steps forward, but it will be up to second-year playcaller Zac Taylor to do so if the Bengals are going to have a chance at exceeding their projected 5.5 win total in 2020.

The Bengals had the first pick in this year’s draft for a plethora of reasons, but near the top of the list was their passing game performance in 2019. Cincinnati ranked 29th in success rate (40%) through the air, 30th in yards per pass attempt (6.5), and 30th in EPA via their passing offense. With that No, 1 pick, the Bengals selected Joe Burrow, who is coming off a historic collegiate season at LSU. On the strength of a 2019 breakout, Burrow enters the NFL ranked in the 95th percentile or above in career yards per pass attempt (9.4), completion rate (68.8%), and touchdown-to-interception ratio at 7.1:1 among all passers invited to the combine since 2000. With Andy Dalton already released this offseason, Burrow is set up to start immediately in Week 1 for the organization.

The Bengals’ passing game was bottom-shelf last season and they struggled to utilize their receiving corps outside of Tyler Boyd, who turned in his second straight 1,000-yard receiving season. Even with Boyd, the Bengals ranked 28th in yards per target (7.1) and 31st in success rate (45%) targeting their wide receivers a year ago. Now, the team is expected to have veteran A.J. Green back in the lineup plus the addition of rookie Tee Higgins at the top of the second round in this year’s draft. Where the Bengals need to improve is using their backfield more optimally in the passing game, especially given the acumen of Joe Mixon and Giovani Bernard in that area. The Bengals were 24th in success rate targeting their backs in 2019 (41%).

The Bengals were a little better in the rushing game than their passing game a year ago, but still were below league marks across the board. The Bengals ranked 23rd in rushing success rate (45%), 24th in yards per carry (3.9 yards), and 20th in EPA through their run game. Joe Mixon rushed for 1,137 yards and ranked 29th in success rate (46%) out of 44 backs with 100 or more carries on the season. The positive here is that Mixon and the run game got better over the back half of the season, with a 49% success rate on the ground Weeks 10-17 after a 41% success rate prior. With Mixon in the final season of his rookie contract, the team still has Giovani Bernard and Trayveon Williams as the primary depth behind Mixon.

Is Joe Burrow a late-round quarterback gem?
We talked about the resume Burrow enters the league with stemming from his historic 2019 production. There’s also volume upside here as Bengals’ passers dropped back 665 times in 2019 (fifth in the league) and ranked eighth in the league in passing rate (61%) in neutral game script outside of the fourth quarter of games. The Bengals project to face our No. 1 fastest schedule in projected pace of play and our No. 8 easiest schedule in projected defenses in passing efficiency for the 2020 season. There have been five quarterbacks picked No. 1 overall in the past decade who have gone on to start all 16 games in year one. The majority of those passers have found fantasy success as rookies in Kyler Murray (QB8 overall in 2019), Jameis Winston (QB13 in 2015), Andrew Luck (QB10 in 2012), Cam Newton (QB3 in 2011), and Sam Bradford (QB20 in 2010). Burrow’s rushing ability is also something that is potentially being severely undervalued. Burrow rushed for 399 and 368 yards in each of his two seasons as a starter, which includes sack yardage. He has an undercover rushing ability similar to an early career Andrew Luck, something that has added value to his passing acumen. Burrow has high upside in his range of outcomes for fantasy if he can acclimate himself to the NFL quickly in his rookie season.
Will 2020 finally be the year Joe Mixon delivers as a full-season, elite fantasy back?
Joe Mixon had 1,424 yards from scrimmage and eight touchdowns in 2019, but fell short of fantasy expectations due to a rollercoaster of a season. He ended up as the RB20 in PPR points per game (14.1), despite receiving a career-high 313 touches. But he did still flash that high-end upside we’ve chased from him. Through nine weeks in 2019, Mixon was a fantasy nightmare. Over those eight games played, Mixon registered just 430 yards from scrimmage (37th) on 120 touches (23rd). Over that span, he was the RB36 in overall scoring on 33.9% of the Cincinnati offensive touches. Then from Weeks 10-17, the Bengals swerved into him as the focal point of their offense. Mixon handled 49.9% of the team's touches over his final eight games while his 193 touches and 994 yards from scrimmage trailed only Christian McCaffrey’s 196 opportunities and 1,148 yards over that span. In that time, Mixon was the RB4 overall in fantasy scoring. Zac Taylor was able to incorporate a scheme that gave Mixon light boxes frequently. The Bengals ran 66% of their rushing plays from 11 personnel, the highest rate in the league in 2020. Not just impacted by end of game runs chasing points, that rate was 60% in the first half of games, which ranked fifth. As a byproduct, Mixon ran into boxes of eight or more defenders on just 7.9% of his carries, which was the third-lowest rate in the league behind Devin Singletary (5.3%) and David Johnson (5.3%). The usage and scheme came on from Mixon in 2019, but the one early career hang up for Mixon has been his lack of involvement in the passing game. After averaging 13.8 yards per receptions with nine receiving scores in college, Mixon has finished no higher than 25th among running backs in receiving points per game over his first three seasons. Over the past two seasons as the lead back, Mixon has still ranked 21st and 17th in routes run for all backs in the league. Even over his end of season breakout a year ago, Mixon still ran fewer pass routes (118) than Giovani Bernard (129). Joe Burrow frequently used a strong pass-catching back such as Clyde Edwards-Helaire a year ago which gives hope that the receiving ceiling can be unlocked for Mixon, but the usage in that role needs to be ramped up firsthand.

The Bengals went on a rare free agent shopping spree this season and the biggest get was D.J. Reader. Reader has been a force on the Houston defensive interior and will now slot next to Geno Atkins to give the Bengals an impressive duo up the middle. Reader was seventh among defensive tackles in pressure rate last season. Even the depth for the Bengals is good on the interior. 2019 fourth-round pick Renell Wren could impress with a bigger role in 2020.
The Bengals find themselves with a good-not-great group of edge rushers. All of Carlos Dunlap, Sam Hubbard, and Carl Lawson were in the top-50 of edge rushers by pressure rate but as a team, the Bengals ranked 27th in ESPN’s Pass Rush Win Rate. Dunlap will be 31 years old this season, which puts pressure on the still-young Hubbard-Lawson duo to play more consistently at a high level.
Josh Bynes wasn’t the biggest splash of the Bengals’ free agent signings but he might be the sneakiest add. Bynes is a good coverage linebacker, which is something the Bengals sorely needed. Cincinnati struggled greatly against tight ends and running backs in coverage last season. Germaine Pratt had as a third-round rookie but with some responsibilities lessened, he could see some improvement.
Linebacker was a big focus for the Bengals in the middle of the draft with three taken in Rounds 3-7. Logan Wilson (third round), Akeem Davis-Gaither (fourth round), and Markus Bailey (seventh round) all have the ability to contribute in their rookie seasons.
The Bengals used base on 29% of their plays last season, which was the 14th-highest rate in the league. Though they also played 20% of Dime+ personnel with just one linebacker on the field.
Cincinnati spent a lot of money on Trae Waynes but might have gotten the better Minnesota corner on a cheap one-year deal with Mackensie Alexander. Meanwhile, William Jackson remains one of the most underrated defensive backs in the league but is in the final year of his rookie deal. That starting trio is more than passable and gives the Bengals a better group than they’ve had in some time, but Waynes is currently the only one signed past 2020.
Jessie Bates and Shawn Williams had their ups and downs last season and the Bengals really struggled with deep coverages. Unfortunately, that’s not where free agent addition Von Bell excels, either. Bates was much better as a deep safety in 2018 and the Bengals could hope he gets back to that level of play.
